-- Danshi Go 后端初始 schema
--
-- 目标：PostgreSQL 18。不使用 GORM AutoMigrate，本文件是 schema 唯一真源。
--
-- ============================================================================
-- 设计原则 1：数据库负责「机械派生」，应用层负责「语义判断」
-- ============================================================================
--
-- updated_at 是语义字段——「内容被编辑」只有业务代码知道算不算。点赞、收藏、
-- 浏览、后台重算计数器都不该动它。因此本 schema **不含任何 updated_at 触发器**，
-- 一律由 GORM 的 autoUpdateTime 在业务写入时维护。
--   ⚠ 推论：view_count 自增等「非内容变更」的写入必须用 GORM 的 UpdateColumn
--     （跳过 hook 与 autoUpdateTime），不能用 Update / Updates。
--
-- 计数器（like_count 等）相反，是纯机械派生：值就是 COUNT(*)，没有语义空间。
-- 旧库交给应用层维护的结果是 31 篇帖子中 16 篇 like_count 漂移且一律偏低，
-- 所以这部分保留触发器，保证与源表同事务一致。
--
-- ============================================================================
-- 设计原则 2：主键一律 bigint identity
-- ============================================================================
--
-- 所有代理主键为 `bigint GENERATED BY DEFAULT AS IDENTITY`，对应 GORM 默认的
-- `ID uint64` 约定。相比 uuid：索引宽度 8 字节而非 16、连接与排序更快、
-- 自增写入天然聚集在 B-tree 右端。
--
-- 用 BY DEFAULT 而非 ALWAYS，是为了让 ETL 能显式指定 id 装载
-- （装载完必须 setval 推进序列，见 data-migration-plan.md §3 与 §5）。
--
--   ⚠ 已知代价：id 可枚举。用户 id 泄露注册总数与注册顺序，帖子 id 可被顺序遍历。
--     内容本身是公开的，但草稿 / 待审帖子的 id 也会落在可枚举区间内，
--     因此**所有按 id 取详情的接口都必须做鉴权，不能依赖 id 不可猜**。
--
-- ============================================================================
-- 相较 Python/Alembic 版本的结构性变更（详见 docs/go-rewrite-plan.md §5.2）
-- ============================================================================
--   1. 全部 uuid 主键          → bigint identity
--   2. tags JSONB              → tags + post_tags 关联表（标签名限 10 字符）
--   3. flavors / preferences JSONB → flavors 字典表 + post_flavors(stance)
--   4. canteen / cuisine 自由文本  → canteens / canteen_windows / cuisines 字典表
--   5. posts.budget_range JSONB    → budget_min / budget_max 列
--   6. posts.images JSONB(URL)     → post_images 关联表 + 真外键
--   7. comments.mentioned_user_ids JSONB → comment_mentions 关联表
--   8. users.avatar_url(text)      → users.avatar_image_asset_id 真外键
--   9. 多态 likes 表               → post_likes / comment_likes + 真外键
--  10. notifications.related_id    → related_post_id / related_comment_id 外键
--  11. notifications.content       → 保留并限长 varchar(100)；type 补 'mention'；
--                                    关联目标由 type 唯一决定（比旧库的 related_type 严格）
--  12. users.hometown              → 删除（无任何读取逻辑的展示字段）
--  13. 计数器改触发器维护；updated_at 触发器全部移除
--  14. 新增 dictionary_suggestions：用户提议词条 → 管理员审核 → 入库并回绑帖子
--  15. 新增 user_sessions：令牌绑定会话，撤销立即生效（旧 logout 是空壳）
--  16. comments 增加 root_id：存真实回复链，展示按楼拍扁；reply_count 改按 root 统计
--  17. comments 软删除：删评论不再连带毁掉他人的回复
--  18. users.is_active → banned_until/ban_reason/banned_by：支持限时封禁
--  19. 新增 moderation_records + image_assets.moderation：机器内容审核，供应商可替换
--  20. users / posts / comments / tags 一律软删除，物理删除由触发器拒绝
--  21. 新增 post_histories / comment_histories：帖子与评论可编辑，逐版保留快照
--  22. 审核覆盖扩展到话题标签与用户昵称/简介；帖子先审后发，其余先发后审

-- +goose Up

-- ============================================================
-- 通用：禁止物理删除
--
-- 产品要求「所有内容一律软删除」。软删除若只是应用层约定，迟早会被一条手写 SQL
-- 或一次误操作绕过，因此和 image_assets 一样用触发器强制：
-- users / posts / comments / tags 的 DELETE 一律拒绝，只能置 deleted_at。
--
-- 运维确需物理清除时，在同一事务内 SET LOCAL danshi.allow_hard_delete = 'on'。
-- 这是事务局部的，不需要表 owner 权限，也不会取 ACCESS EXCLUSIVE 锁。
--
-- ⚠ 关联表（post_likes / favorites / follows / post_tags / post_flavors / post_images
--   / comment_mentions）**不在此列**，它们是「动作」不是「内容」：
--   取消点赞就该真的删行——复合主键决定了软删的行会永久占位、让用户无法再次点赞。
-- ============================================================

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION danshi_forbid_row_update()
RETURNS trigger
LANGUAGE plpgsql
AS $func$
BEGIN
  RAISE EXCEPTION
    '% 是追加不可篡改的记录，禁止修改。需要更正请追加新记录并指向被更正的那一条。', TG_TABLE_NAME
    USING ERRCODE = 'restrict_violation';
END;
$func$;
-- +goose StatementEnd

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION danshi_forbid_hard_delete()
RETURNS trigger
LANGUAGE plpgsql
AS $func$
BEGIN
  IF current_setting('danshi.allow_hard_delete', true) IS NOT DISTINCT FROM 'on' THEN
    RETURN OLD;
  END IF;
  RAISE EXCEPTION
    '% 不允许物理删除（内容表请改为软删除，审计表本就只能追加）；'
    '运维清除请在同一事务内 SET LOCAL danshi.allow_hard_delete = ''on''', TG_TABLE_NAME
    USING ERRCODE = 'restrict_violation';
END;
$func$;
-- +goose StatementEnd


-- ============================================================
-- 字典表：canteens / canteen_windows / cuisines / flavors
--
-- 这些旧库是帖子上的自由文本列，前端 config_service.ts 里另有一份硬编码
-- 词表（且后端从未提供 /config 端点，四个 fetcher 全是本地 fallback）。
-- 提升为字典表后：筛选变成外键连接而非中文字符串相等；餐厅可以改名或停用
-- 而不必回写所有历史帖子；后端终于能真的实现 /config 与管理端词表维护接口。
--
-- 词表由后端写死（种子见 00002），前端只做选择，不能自由填写。
-- 用户想要新词条走 dictionary_suggestions 提议流程（见文件末尾）。
-- ============================================================

CREATE TABLE canteens (
    id         bigint       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    code       varchar(64)  NOT NULL,
    name       varchar(100) NOT NULL,
    campus     varchar(50)  NOT NULL,
    sort_order integer      NOT NULL DEFAULT 0,
    is_active  boolean      NOT NULL DEFAULT true,
    created_at timestamptz  NOT NULL DEFAULT now(),
    updated_at timestamptz  NOT NULL DEFAULT now()
);

ALTER TABLE canteens
    ADD CONSTRAINT canteens_code_trimmed_check CHECK (code = btrim(code) AND btrim(code) <> ''),
    ADD CONSTRAINT canteens_name_trimmed_check CHECK (name = btrim(name) AND btrim(name) <> ''),
    ADD CONSTRAINT canteens_campus_trimmed_check CHECK (campus = btrim(campus) AND btrim(campus) <> '');

CREATE UNIQUE INDEX uq_canteens_code ON canteens (code);
CREATE UNIQUE INDEX uq_canteens_name ON canteens (name);

COMMENT ON TABLE  canteens IS
  '餐厅/食堂字典。由 00002 迁移种子化，之后由管理端接口维护。'
  '一个帖子对应一个餐厅，餐厅下可以再细分窗口（canteen_windows）。';
COMMENT ON COLUMN canteens.code IS
  '对外稳定标识，/config 端点以此作为 CanteenConfig.id 返回（前端既有取值如 canteen-south）。名称可改，code 不可改。';
COMMENT ON COLUMN canteens.campus IS '所属校区，用于前端按校区分组，如「邯郸校区」「江湾校区」。';
COMMENT ON COLUMN canteens.is_active IS '停用后不再出现在 /config 选项中，但历史帖子的外键仍然有效。';

-- ------------------------------------------------------------
-- canteen_windows：餐厅下的窗口
--
-- 产品形态：帖子 → 餐厅（可空）→ 窗口（可空）。用户常常不知道具体窗口，
-- 所以窗口允许留空；但只要填了，就必须是所选餐厅名下的窗口。
-- 这条一致性由 posts 上的**复合外键**声明式保证，无需触发器或应用层校验：
--   FOREIGN KEY (canteen_window_id, canteen_id) → canteen_windows (id, canteen_id)
-- 外键默认 MATCH SIMPLE：任一列为 NULL 即跳过检查，恰好实现「窗口可空」。
--
-- 为未来的「某窗口下有哪些帖子」页面预留：posts.canteen_window_id 上有偏索引。
-- ------------------------------------------------------------

CREATE TABLE canteen_windows (
    id         bigint       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    canteen_id bigint       NOT NULL REFERENCES canteens (id) ON DELETE CASCADE,
    name       varchar(100) NOT NULL,
    floor      varchar(20),
    sort_order integer      NOT NULL DEFAULT 0,
    is_active  boolean      NOT NULL DEFAULT true,
    created_at timestamptz  NOT NULL DEFAULT now(),
    updated_at timestamptz  NOT NULL DEFAULT now(),

    -- 只拒空白不够：' 1F' / '1F ' / '1F' 会被当成三个不同楼层，绕过唯一约束
    CONSTRAINT canteen_windows_name_trimmed_check
        CHECK (name = btrim(name) AND btrim(name) <> ''),
    CONSTRAINT canteen_windows_floor_trimmed_check
        CHECK (floor IS NULL OR (floor = btrim(floor) AND btrim(floor) <> '')),
    -- 同餐厅同楼层内窗口名唯一。NULLS NOT DISTINCT（PG15+）让「楼层未填」也参与判重，
    -- 否则两条都不填楼层的同名窗口会被放过。
    CONSTRAINT uq_canteen_windows_name UNIQUE NULLS NOT DISTINCT (canteen_id, floor, name),
    -- id 已是主键，此唯一约束逻辑上冗余，但 PostgreSQL 要求被复合外键引用的
    -- 列组必须存在唯一约束，posts 与 dictionary_suggestions 的复合外键依赖它。请勿删除。
    CONSTRAINT uq_canteen_windows_id_canteen UNIQUE (id, canteen_id)
);

CREATE INDEX idx_canteen_windows_canteen ON canteen_windows (canteen_id, sort_order);

COMMENT ON TABLE canteen_windows IS
  '餐厅窗口。种子为空，由管理端录入或经 dictionary_suggestions 审核后创建。';
COMMENT ON COLUMN canteen_windows.canteen_id IS
  '所属餐厅。餐厅被删除时窗口一并级联删除（但餐厅通常只停用不删除）。';
COMMENT ON COLUMN canteen_windows.floor IS
  '楼层，可空——很多窗口没有明确楼层，或用户填不出来。'
  '用 varchar 而非整数是为了容纳「B1」「负一层」「夹层」这类非数字写法。'
  '参与同餐厅内的窗口名判重（同名不同层视为两个窗口）。';

CREATE TABLE cuisines (
    id         bigint      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name       varchar(50) NOT NULL,
    sort_order integer     NOT NULL DEFAULT 0,
    is_active  boolean     NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE cuisines
    ADD CONSTRAINT cuisines_name_trimmed_check CHECK (name = btrim(name) AND btrim(name) <> '');

CREATE UNIQUE INDEX uq_cuisines_name ON cuisines (name);

COMMENT ON TABLE  cuisines IS '菜系字典，如「中式」「日式」。取值同时是 API 对外的字符串。';
COMMENT ON COLUMN cuisines.sort_order IS '/config 返回顺序，越小越靠前。';

CREATE TABLE flavors (
    id         bigint      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name       varchar(50) NOT NULL,
    sort_order integer     NOT NULL DEFAULT 0,
    is_active  boolean     NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE flavors
    ADD CONSTRAINT flavors_name_trimmed_check CHECK (name = btrim(name) AND btrim(name) <> '');

CREATE UNIQUE INDEX uq_flavors_name ON flavors (name);

COMMENT ON TABLE flavors IS
  '口味字典。种子取自前端既有词表，其中「川菜/湘菜/粤菜」其实是菜系、'
  '「微辣/中辣/特辣/麻辣/香辣」是同一维度的档位——分类学上不干净，'
  '但属产品口径问题，此处按现状种子化，重新划分需单独决策。';


-- ============================================================
-- tags：自由标签，用户可任意创建
--
-- 与上面几张字典表不同，tags 是开放集合：用户输入什么就有什么，不走审核。
-- 之所以也建表而不留 text[]，是为了支撑按标签检索、标签重命名与合并、
-- 以及热门标签统计（用 post_tags 上的 GROUP BY 现算，不做冗余计数列）。
--
-- 因为开放，所以必须限流：单个标签最长 10 字符，单帖最多 10 个标签
-- （后者是行数上限，在应用层校验）。
-- ============================================================

CREATE TABLE tags (
    id         bigint      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name       varchar(10) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    -- 机审结论：标签是用户自由创建的，走「先发后审」
    moderation varchar(16) NOT NULL DEFAULT 'pending',
    deleted_at timestamptz,

    CONSTRAINT tags_name_not_blank_check CHECK (btrim(name) <> ''),
    -- varchar(10) 已限长；此约束额外排除「首尾空白凑长度」的绕过写法
    CONSTRAINT tags_name_trimmed_check   CHECK (name = btrim(name)),
    CONSTRAINT tags_moderation_check
        CHECK (moderation IN ('pending', 'pass', 'review', 'block'))
);

CREATE TRIGGER trg_tags_forbid_delete
    BEFORE DELETE ON tags
    FOR EACH ROW EXECUTE FUNCTION danshi_forbid_hard_delete();

-- 大小写不敏感唯一：中文无大小写，但英文标签 Spicy / spicy 应视为同一个。
-- 应用层负责写入前 trim + NFKC 归一化。
CREATE UNIQUE INDEX uq_tags_name_lower ON tags (lower(name));

COMMENT ON TABLE  tags IS
  '用户自由标签，无需审核。长度上限 10 字符由列类型与 CHECK 双重保证；'
  '单帖标签数上限（10 个）是行数约束，由应用层校验。';
COMMENT ON COLUMN tags.name IS '展示原文，保留用户输入的大小写；唯一性按 lower(name) 判定。';
COMMENT ON COLUMN tags.moderation IS
  '机审结论。标签走「先发后审」：创建即可用，机审异步跟进；'
  'block 时置 deleted_at 下架，该标签从所有帖子的展示中消失，但 post_tags 关联行保留以便误杀恢复。';
COMMENT ON COLUMN tags.deleted_at IS '非空表示已下架（违规或被合并）。物理删除被触发器拒绝。';


-- ============================================================
-- users
-- ============================================================

CREATE TABLE users (
    id              bigint       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email           varchar(255) NOT NULL,
    password_hash   varchar(255) NOT NULL,
    name            varchar(100) NOT NULL DEFAULT '',
    gender          varchar(10),
    bio             text,
    -- 头像外键在 image_assets 建表后追加（两表互相引用）
    avatar_image_asset_id bigint,
    role            varchar(20)  NOT NULL DEFAULT 'user',
    -- 封禁：取代旧库的布尔 is_active，支持限时与永久两种。
    -- 刻意**不用** timestamptz 的 'infinity' 表示永久：PostgreSQL 侧比较没问题，
    -- 但 pgx 用 pgtype.Timestamptz.InfinityModifier 单独表示无穷时间，
    -- GORM 模型若直接用 *time.Time 会扫描失败或序列化出意外结果。
    -- 用一个显式布尔换掉这个坑，代价只是多一列。
    --   未封禁：ban_is_permanent=false 且 banned_until IS NULL
    --   永久：  ban_is_permanent=true  且 banned_until IS NULL
    --   限时：  ban_is_permanent=false 且 banned_until=到期时刻（到期自动解封，无需定时任务）
    -- 判定是否处于封禁中：ban_is_permanent OR banned_until > now()
    ban_is_permanent boolean     NOT NULL DEFAULT false,
    banned_until    timestamptz,
    ban_reason      varchar(200),
    -- 可空：旧库的停用记录没有操作人，迁移时如实留空即可。
    -- 新产生的封禁由应用层负责填上，数据库不强制——
    -- 强制的代价是迁移只能随便挑个管理员顶上，那反而是往审计数据里写假信息。
    banned_by       bigint,
    -- 注销：软删除。硬删用户会经 author_id 级联抹掉其全部帖子与评论，
    -- 连带毁掉他人挂在其评论下的回复，与「删除不得伤及他人」直接冲突。
    deleted_at      timestamptz,
    created_at      timestamptz  NOT NULL DEFAULT now(),
    updated_at      timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT users_role_check   CHECK (role IN ('user', 'admin', 'super_admin')),
    CONSTRAINT users_gender_check CHECK (gender IS NULL OR gender IN ('male', 'female', 'other')),
    CONSTRAINT users_email_format_check CHECK (position('@' IN email) > 1),
    -- 永久与限时互斥：永久封禁不该再有到期时间
    CONSTRAINT users_ban_kind_check
        CHECK (NOT (ban_is_permanent AND banned_until IS NOT NULL)),
    -- 既然决定用布尔表达永久，就要把 infinity 这条后门也关上，
    -- 否则仍可写出 banned_until='infinity'，pgx/GORM 的无穷时间映射坑照样触发。
    CONSTRAINT users_ban_until_finite_check
        CHECK (banned_until IS NULL OR isfinite(banned_until)),
    -- 封禁要素成组。⚠ 必须显式写 ban_reason IS NOT NULL：
    -- btrim(NULL) <> '' 求值为 NULL，而 CHECK 只拒绝 FALSE 不拒绝 NULL，
    -- 少了这一句就能写出「封禁了但没有理由」。
    -- 封禁要素成组：封禁时理由必填，未封禁时理由与操作人都必须为空。
    -- ⚠ 必须显式写 ban_reason IS NOT NULL：btrim(NULL) <> '' 求值为 NULL，
    -- 而 CHECK 只拒绝 FALSE 不拒绝 NULL，少了这一句就能写出「封禁了但没有理由」。
    CONSTRAINT users_ban_fields_check CHECK (
        CASE WHEN ban_is_permanent OR banned_until IS NOT NULL
             THEN ban_reason IS NOT NULL AND btrim(ban_reason) <> ''
             ELSE ban_reason IS NULL AND banned_by IS NULL
        END
    )
);

-- 用 RESTRICT 而非 SET NULL：SET NULL 会在管理员账号被删时抹掉执行人，
-- 既丢失留痕，又直接违反上面「封禁时 banned_by 必须非空」的约束。
ALTER TABLE users
    ADD CONSTRAINT fk_users_banned_by FOREIGN KEY (banned_by) REFERENCES users (id) ON DELETE RESTRICT;

-- 后台「当前被封禁的用户」列表
CREATE INDEX idx_users_banned ON users (banned_until)
    WHERE ban_is_permanent OR banned_until IS NOT NULL;

-- 邮箱大小写不敏感唯一。旧库是区分大小写的 UNIQUE(email)，Foo@x 与 foo@x 可同时存在，属缺陷。
CREATE UNIQUE INDEX uq_users_email_lower ON users (lower(email));
CREATE INDEX idx_users_created_at ON users (created_at DESC);

COMMENT ON TABLE users IS
  '账号主体。封禁用 is_active，不物理删除——帖子、评论的外键都是 CASCADE，删用户会连带抹掉内容。';
COMMENT ON COLUMN users.email IS
  '注册时域名白名单由应用层 ALLOWED_EMAIL_DOMAINS 校验（fdueat.com / m.fudan.edu.cn / fudan.edu.cn）；登录不校验域名，存量非合规邮箱豁免。';
COMMENT ON COLUMN users.password_hash IS 'bcrypt，与 Python 侧二进制兼容，迁移后旧密码可直接登录。';
COMMENT ON COLUMN users.name IS '展示昵称，非唯一。空串表示未设置（非 NULL，简化前端处理）。';
COMMENT ON COLUMN users.gender IS
  '可空。前端 Gender 类型只产出 male / female，other 予以保留但前端不会提交。'
  '修改入口是 PUT 用户资料接口（update_user_profile），与 name / bio / 头像同一个接口。';
COMMENT ON COLUMN users.role IS 'user 普通用户；admin 可审核帖子与维护词表；super_admin 额外可管理用户与管理员。';
COMMENT ON COLUMN users.ban_is_permanent IS
  '是否永久封禁。与 banned_until 互斥：永久封禁时 banned_until 必须为空。'
  '用显式布尔而不是 timestamptz 的 ''infinity''，是为了避开 pgx/GORM 对无穷时间的类型映射坑。';
COMMENT ON COLUMN users.banned_until IS
  '限时封禁的到期时刻，永久封禁与未封禁时均为空。到期即自动解封，不需要定时任务扫表。'
  '完整判定：**ban_is_permanent OR banned_until > now()** 表示处于封禁中。'
  '被封期间登录被拒、已有会话应一并撤销；已发布内容保留可见，删内容是另一个动作。';
COMMENT ON COLUMN users.ban_reason IS '封禁理由，会展示给被封用户，因此要写成人能看懂的话。';
COMMENT ON COLUMN users.banned_by IS
  '执行封禁的管理员。**可空**：迁移自旧库的停用记录没有操作人，如实留空即可；'
  '新产生的封禁由应用层填上。外键用 RESTRICT：留痕不能因为管理员账号被删就消失。';
COMMENT ON COLUMN users.avatar_image_asset_id IS
  '头像资产。注册时必须为空，用户登录后自行上传；只能引用自己上传的 purpose=avatar 资产（应用层校验）。';
COMMENT ON COLUMN users.deleted_at IS
  '账号注销时间。非空表示已注销：不能登录、不出现在搜索与用户列表中，'
  '但其已发布内容保留（作者展示为「已注销用户」）。物理删除被 trg_users_forbid_delete 拒绝。';
COMMENT ON COLUMN users.updated_at IS '由应用层（GORM autoUpdateTime）维护，无数据库触发器。';

CREATE INDEX idx_users_deleted ON users (deleted_at) WHERE deleted_at IS NOT NULL;

CREATE TRIGGER trg_users_forbid_delete
    BEFORE DELETE ON users
    FOR EACH ROW EXECUTE FUNCTION danshi_forbid_hard_delete();


-- ============================================================
-- image_assets
-- ============================================================

CREATE TABLE image_assets (
    id           bigint       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uploader_id  bigint       REFERENCES users (id) ON DELETE SET NULL,
    purpose      varchar(32)  NOT NULL DEFAULT 'post',
    object_key   varchar(512) NOT NULL,
    public_url   text         NOT NULL,
    content_type varchar(100) NOT NULL,
    size         bigint,
    status       varchar(20)  NOT NULL DEFAULT 'pending',
    -- 机器审核结论，与 status（引用状态）是两个正交维度
    moderation   varchar(16)  NOT NULL DEFAULT 'pending',
    created_at   timestamptz  NOT NULL DEFAULT now(),
    updated_at   timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT image_assets_status_check  CHECK (status IN ('pending', 'ready', 'retired')),
    CONSTRAINT image_assets_moderation_check
        CHECK (moderation IN ('pending', 'pass', 'review', 'block')),
    CONSTRAINT image_assets_purpose_check CHECK (purpose IN ('post', 'avatar')),
    CONSTRAINT image_assets_size_check    CHECK (size IS NULL OR size > 0)
);

-- 旧库实测 duplicate_image_object_keys = 0、duplicate_image_public_urls = 0，可安全建唯一约束。
-- public_url 唯一是 ETL 反查资产 id 的前提。
CREATE UNIQUE INDEX uq_image_assets_object_key ON image_assets (object_key);
CREATE UNIQUE INDEX uq_image_assets_public_url ON image_assets (public_url);
CREATE INDEX idx_image_assets_uploader_created ON image_assets (uploader_id, created_at);
CREATE INDEX idx_image_assets_status_created   ON image_assets (status, created_at)
    WHERE status = 'pending';

COMMENT ON TABLE image_assets IS
  '上传的图片资产。禁止物理删除（trg_image_assets_forbid_delete），业务侧只能标 retired，'
  '运维侧走 danshi_purge_image_assets()。这样对象存储里的文件不会被悄悄孤立。';
COMMENT ON COLUMN image_assets.purpose IS
  'post 帖子配图；avatar 头像。上传时确定，引用方必须匹配（应用层校验）。';
COMMENT ON COLUMN image_assets.object_key IS '对象存储内的键，删除远端文件时使用。';
COMMENT ON COLUMN image_assets.status IS
  'pending 已上传但未被任何内容引用（可被清理任务回收）；ready 已被引用；retired 曾被引用但引用已全部解除。';
COMMENT ON COLUMN image_assets.uploader_id IS
  '上传者。用户注销后置空但资产保留，避免已发布帖子图片失效。';
COMMENT ON COLUMN image_assets.moderation IS
  '机器审核结论，与 status 正交（status 说的是「有没有被引用」，本列说的是「内容合不合规」）。'
  'pending 待审；pass 通过；review 需人工复核；block 判定违规。'
  '审核是异步的，用户点发布时图片可能还没审完，因此**允许引用尚在 pending/review 的图片**，'
  '只有 block 不可引用；真正的约束是「引用了未通过图片的帖子不得进入已发布状态」，'
  '这是跨表规则，由服务层单事务校验（见 go-rewrite-plan §5.2.9）。审核明细见 moderation_records。';
CREATE INDEX idx_image_assets_moderation ON image_assets (moderation, created_at)
    WHERE moderation IN ('pending', 'review');

-- 头像外键：与 image_assets 互相引用，故延后到此处追加并设为可延迟，方便 ETL 按任意顺序装载。
ALTER TABLE users
    ADD CONSTRAINT fk_users_avatar_image_asset
    FOREIGN KEY (avatar_image_asset_id) REFERENCES image_assets (id)
    ON DELETE SET NULL
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX idx_users_avatar_image_asset ON users (avatar_image_asset_id)
    WHERE avatar_image_asset_id IS NOT NULL;


-- ------------------------------------------------------------
-- image_assets：禁止物理删除（沿用 Python 版本的防线）
-- ------------------------------------------------------------

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION danshi_forbid_image_asset_delete()
RETURNS trigger
LANGUAGE plpgsql
AS $func$
BEGIN
  IF current_setting('danshi.allow_image_asset_delete', true)
     IS NOT DISTINCT FROM 'on' THEN
    RETURN OLD;
  END IF;
  RAISE EXCEPTION
    'image_assets 不允许物理删除。业务删除请将 status 标为 retired；'
    '运维删除请在同一事务内 SET LOCAL danshi.allow_image_asset_delete = ''on''，'
    '或调用 danshi_purge_image_assets(bigint[])'
    USING ERRCODE = 'restrict_violation';
END;
$func$;
-- +goose StatementEnd

CREATE TRIGGER trg_image_assets_forbid_delete
    BEFORE DELETE ON image_assets
    FOR EACH ROW EXECUTE FUNCTION danshi_forbid_image_asset_delete();

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION danshi_purge_image_assets(p_ids bigint[])
RETURNS integer
LANGUAGE plpgsql
AS $func$
DECLARE
  deleted_count integer;
  prev_asset    text;
  prev_hard     text;
BEGIN
  -- 两个逃生阀都要开：删资产会经 CASCADE 带走它的审核流水，
  -- 而审核流水的禁删触发器看的是 danshi.allow_hard_delete。
  -- Grandfather 上线后每张历史图片都有审核记录，不开这个阀 purge 会全线失败。
  prev_asset := current_setting('danshi.allow_image_asset_delete', true);
  prev_hard  := current_setting('danshi.allow_hard_delete', true);
  PERFORM set_config('danshi.allow_image_asset_delete', 'on', true);
  PERFORM set_config('danshi.allow_hard_delete', 'on', true);

  DELETE FROM image_assets WHERE id = ANY (p_ids);
  GET DIAGNOSTICS deleted_count = ROW_COUNT;

  -- 保存并恢复，不能只置位：set_config 的第三参数是事务局部不是函数局部，
  -- 只置位会让后续任意资产删除、任意审计表删除在同一事务里全部放行。
  PERFORM set_config('danshi.allow_image_asset_delete', COALESCE(prev_asset, ''), true);
  PERFORM set_config('danshi.allow_hard_delete', COALESCE(prev_hard, ''), true);
  RETURN deleted_count;
END;
$func$;
-- +goose StatementEnd

COMMENT ON FUNCTION danshi_purge_image_assets(bigint[]) IS
  '运维通道：真正删除资产行。仅在远端对象已删除后调用。';


-- ============================================================
-- posts
-- ============================================================

CREATE TABLE posts (
    id                bigint        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    author_id         bigint        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    post_type         varchar(20)   NOT NULL,
    share_type        varchar(20),
    status            varchar(20)   NOT NULL DEFAULT 'pending',
    category          varchar(20)   NOT NULL,
    title             varchar(200)  NOT NULL,
    content           text          NOT NULL,
    canteen_id        bigint        REFERENCES canteens (id) ON DELETE RESTRICT,
    canteen_window_id bigint,
    cuisine_id        bigint        REFERENCES cuisines (id) ON DELETE RESTRICT,
    price             numeric(10,2),
    -- 由 JSONB budget_range 拍平
    budget_min        integer,
    budget_max        integer,
    like_count        integer       NOT NULL DEFAULT 0,
    favorite_count    integer       NOT NULL DEFAULT 0,
    comment_count     integer       NOT NULL DEFAULT 0,
    view_count        integer       NOT NULL DEFAULT 0,
    deleted_at        timestamptz,
    deleted_reason    varchar(16),
    deleted_by        bigint        REFERENCES users (id) ON DELETE RESTRICT,
    created_at        timestamptz   NOT NULL DEFAULT now(),
    updated_at        timestamptz   NOT NULL DEFAULT now(),

    -- 枚举。'companion' 被刻意排除：旧库仅 1 行且不迁移（见 data-migration-plan.md §2）。
    CONSTRAINT posts_post_type_check  CHECK (post_type IN ('share', 'seeking')),
    CONSTRAINT posts_share_type_check CHECK (share_type IS NULL OR share_type IN ('recommend', 'warning')),
    CONSTRAINT posts_status_check     CHECK (status IN ('draft', 'pending', 'approved', 'rejected')),
    -- 约束名沿用旧库：Python 版 error_handlers 对该名称有专门的中文提示映射。
    CONSTRAINT posts_category_check   CHECK (category IN ('food', 'recipe')),

    -- 把原先只在 Pydantic 层的条件校验下沉到数据库：
    -- 求推荐帖不得携带 share_type；分享帖除草稿外必须有 share_type。
    CONSTRAINT posts_seeking_no_share_type_check
        CHECK (post_type <> 'seeking' OR share_type IS NULL),
    CONSTRAINT posts_share_requires_share_type_check
        CHECK (post_type <> 'share' OR status = 'draft' OR share_type IS NOT NULL),

    -- 窗口可以为空，但填了窗口就必须同时填餐厅。
    -- 「窗口属于该餐厅」由下方复合外键保证（MATCH SIMPLE 在任一列为 NULL 时跳过检查，
    -- 因此这条 CHECK 是必需的补充，否则 canteen_id 为空时复合外键会失效）。
    CONSTRAINT posts_window_requires_canteen_check
        CHECK (canteen_window_id IS NULL OR canteen_id IS NOT NULL),
    CONSTRAINT fk_posts_canteen_window
        FOREIGN KEY (canteen_window_id, canteen_id)
        REFERENCES canteen_windows (id, canteen_id) ON DELETE RESTRICT,

    CONSTRAINT posts_price_check       CHECK (price IS NULL OR price >= 0),
    -- PRD 的帖子类型表把这两项写成「不适用」，就不该允许写进来：
    -- 人均价格只对分享帖有意义，预算区间只对提问帖有意义。
    CONSTRAINT posts_price_share_only_check
        CHECK (price IS NULL OR post_type = 'share'),
    CONSTRAINT posts_budget_seeking_only_check
        CHECK (budget_min IS NULL OR post_type = 'seeking'),
    CONSTRAINT posts_budget_pair_check CHECK ((budget_min IS NULL) = (budget_max IS NULL)),
    CONSTRAINT posts_budget_range_check
        CHECK (budget_min IS NULL OR (budget_min >= 0 AND budget_max >= budget_min)),
    CONSTRAINT posts_counters_check
        CHECK (like_count >= 0 AND favorite_count >= 0 AND comment_count >= 0 AND view_count >= 0),
    CONSTRAINT posts_delete_pair_check CHECK (
        CASE WHEN deleted_at IS NULL
             THEN deleted_reason IS NULL AND deleted_by IS NULL
             ELSE deleted_reason IS NOT NULL
        END
    ),
    CONSTRAINT posts_delete_reason_check
        CHECK (deleted_reason IS NULL OR deleted_reason IN ('author', 'admin', 'moderation'))
);

-- 供 post_flavors 的复合外键引用：口味立场必须与帖子类型匹配
ALTER TABLE posts ADD CONSTRAINT uq_posts_id_post_type UNIQUE (id, post_type);
-- 供 comments 的复合外键引用：楼主评论的「回复对象」必须是帖子作者
ALTER TABLE posts ADD CONSTRAINT uq_posts_id_author UNIQUE (id, author_id);

CREATE TRIGGER trg_posts_forbid_delete
    BEFORE DELETE ON posts
    FOR EACH ROW EXECUTE FUNCTION danshi_forbid_hard_delete();

CREATE INDEX idx_posts_deleted ON posts (deleted_at DESC) WHERE deleted_at IS NOT NULL;

CREATE INDEX idx_posts_author_created  ON posts (author_id, created_at DESC);
CREATE INDEX idx_posts_status_created  ON posts (status, created_at DESC);
CREATE INDEX idx_posts_category        ON posts (category);
CREATE INDEX idx_posts_canteen         ON posts (canteen_id) WHERE canteen_id IS NOT NULL;
CREATE INDEX idx_posts_cuisine         ON posts (cuisine_id) WHERE cuisine_id IS NOT NULL;
-- 为规划中的「某窗口下有哪些帖子」页面预留；按窗口 + 时间倒序取列表
CREATE INDEX idx_posts_window_created  ON posts (canteen_window_id, created_at DESC)
    WHERE canteen_window_id IS NOT NULL;

COMMENT ON TABLE posts IS
  '帖子。两个正交维度：post_type（分享 / 求推荐）与 category（食堂菜品 / 自制菜谱）。'
  '地点是「餐厅 → 窗口」两级，两级都可空。';
COMMENT ON COLUMN posts.post_type IS
  'share 分享型：作者已经吃过，输出体验，须配 share_type；'
  'seeking 求助型：作者还没吃，征集推荐，用 budget_* 与 post_flavors(prefer/avoid) 表达诉求。';
COMMENT ON COLUMN posts.share_type IS
  'recommend 安利 / warning 避雷。仅 post_type=share 使用；草稿允许暂缺。';
COMMENT ON COLUMN posts.category IS
  'food 食堂菜品 / recipe 自制菜谱。与 post_type 正交：两种 post_type 都可以是任一 category。';
COMMENT ON COLUMN posts.canteen_id IS '所属餐厅。可空（用户可以不指明地点）。';
COMMENT ON COLUMN posts.canteen_window_id IS
  '餐厅下的具体窗口。可空——用户往往不知道窗口名。'
  '非空时由复合外键保证该窗口确实属于 canteen_id 指向的餐厅。';
COMMENT ON COLUMN posts.price IS
  '人均价格，仅 share 型有意义。API 以字符串收发（decimal 语义），后端用 shopspring/decimal 解析，禁止用 float。';
COMMENT ON COLUMN posts.budget_min IS
  '预算下限（元，整数）。仅 seeking 型有意义。与 budget_max 必须同时有值或同时为空。';
COMMENT ON COLUMN posts.view_count IS
  '浏览计数，由应用层在帖子详情接口自增。⚠ 必须用 GORM UpdateColumn 写入，'
  '否则 autoUpdateTime 会把「有人看了一眼」误记成「内容被编辑」。';
COMMENT ON COLUMN posts.like_count IS '由触发器与 post_likes 同事务维护，应用层禁止直接写。';
COMMENT ON COLUMN posts.updated_at IS
  '「内容被编辑」的时间。点赞/收藏/评论/浏览/后台重算一律不改动它——'
  '这是本 schema 不设 updated_at 触发器的原因。每次编辑同时向 post_histories 追加一条快照。';
COMMENT ON COLUMN posts.deleted_at IS
  '软删除标记。非空即视为已删除：不出现在任何列表与详情中，但行保留，'
  '评论与历史快照一并保留，便于申诉与误杀恢复。物理删除被 trg_posts_forbid_delete 拒绝。';
COMMENT ON COLUMN posts.deleted_reason IS 'author 作者自删；admin 管理员删；moderation 机审判违规。';
COMMENT ON COLUMN posts.status IS
  'draft 仅作者可见的草稿；pending 已提交、等待机审或人工审核；approved 审核通过公开可见；rejected 审核驳回。'
  '帖子走「先审后发」：提交后先机审，机审通过直接 approved，判需复核则停在 pending 等人工裁决。';



-- ============================================================
-- post_tags / post_flavors：取代 tags、flavors、preferences 三个 JSONB
-- ============================================================

CREATE TABLE post_tags (
    post_id bigint NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    tag_id  bigint NOT NULL REFERENCES tags (id) ON DELETE RESTRICT,

    PRIMARY KEY (post_id, tag_id)
);

CREATE INDEX idx_post_tags_tag ON post_tags (tag_id);

COMMENT ON TABLE post_tags IS
  '帖子↔标签。反向索引 idx_post_tags_tag 支撑「按标签查帖子」与热门标签 GROUP BY 统计。'
  'tag 侧用 RESTRICT：删标签前必须先解除引用，避免误删打散历史数据。';

-- stance 与帖子类型必须匹配：分享帖只能 has（描述事实），提问帖只能 prefer/avoid（表达诉求）。
-- 这条不变量跨了两张表，用冗余列 post_type + 复合外键声明式保证，
-- 手法与 comments 的 effective_root_id 一致：冗余列由复合外键锚定，不可能与 posts 不一致。
CREATE TABLE post_flavors (
    post_id   bigint      NOT NULL,
    flavor_id bigint      NOT NULL REFERENCES flavors (id) ON DELETE RESTRICT,
    stance    varchar(10) NOT NULL,
    post_type varchar(20) NOT NULL,

    PRIMARY KEY (post_id, flavor_id),
    CONSTRAINT post_flavors_stance_check CHECK (stance IN ('has', 'prefer', 'avoid')),
    CONSTRAINT post_flavors_stance_matches_type_check
        CHECK ((post_type = 'share') = (stance = 'has')),
    CONSTRAINT fk_post_flavors_post
        FOREIGN KEY (post_id, post_type) REFERENCES posts (id, post_type) ON DELETE CASCADE
);

CREATE INDEX idx_post_flavors_flavor ON post_flavors (flavor_id, stance);

COMMENT ON TABLE post_flavors IS
  '帖子↔口味。一张表覆盖旧库的三个数组：flavors → stance=has；'
  'preferences.prefer_flavors → prefer；preferences.avoid_flavors → avoid。';
COMMENT ON COLUMN post_flavors.stance IS
  'has 该分享帖具有此口味；prefer 提问帖希望有；avoid 提问帖希望避开。'
  '主键 (post_id, flavor_id) 天然杜绝同一口味既 prefer 又 avoid；'
  '复合外键 (post_id, post_type) 保证立场与帖子类型匹配。';
COMMENT ON COLUMN post_flavors.post_type IS
  '冗余自 posts.post_type，仅用于支撑 stance 与帖子类型的匹配约束。'
  '由复合外键锚定，不可能与 posts 不一致；应用层插入时照抄帖子的 post_type 即可。';


-- ============================================================
-- post_images：取代 posts.images JSONB
-- ============================================================

CREATE TABLE post_images (
    post_id        bigint   NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    position       smallint NOT NULL,
    image_asset_id bigint   NOT NULL REFERENCES image_assets (id) ON DELETE RESTRICT,
    created_at     timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (post_id, position),
    -- 单帖最多 9 张，与原 Pydantic 校验一致
    CONSTRAINT post_images_position_check CHECK (position >= 0 AND position < 9),
    -- 主键只保证同一 position 唯一，不阻止同一张图在一个帖子里出现两次
    CONSTRAINT uq_post_images_post_asset UNIQUE (post_id, image_asset_id)
);

CREATE INDEX idx_post_images_asset ON post_images (image_asset_id);

COMMENT ON TABLE post_images IS
  '帖子图片。旧库把 public_url 字符串存在 posts.images JSONB 里，与 image_assets 无外键关系，'
  '导致资产退役只能靠触发器做 URL 字符串匹配。此表把该关系变为声明式。';
COMMENT ON COLUMN post_images.position IS '展示顺序，从 0 起。主键含 position，故同帖顺序天然唯一。';


-- ============================================================
-- comments
-- ============================================================

-- 存储保留真实回复链（可任意深），展示时按 root 拍扁成两层。
--
-- 三种写入行为：
--   1. 点帖子的评论按钮        → parent_id = NULL,           root_id = NULL,
--                                reply_to_user_id = post.author_id
--   2. 点某条 root 评论的回复  → parent_id = root.id,        root_id = root.id,
--                                reply_to_user_id = parent.author_id
--   3. 点某条非 root 评论的回复 → parent_id = parent.id,      root_id = parent.root_id,
--                                reply_to_user_id = parent.author_id
--
-- 也就是：parent_id 记录「回复的是谁」，root_id 记录「挂在哪个楼下」。
-- 前端只需按 root_id 分组即可拍扁呈现，无需递归；后端保留 parent 链以便日后
-- 需要还原真实层级或做「回复 @某人」溯源。
--
-- 三条不变式全部由一个复合外键声明式保证，不依赖应用层自觉：
--   (a) parent 与 root 必须同时为空或同时非空（要么是根评论，要么是回复）
--   (b) 回复必须与父评论在同一帖子下 —— 否则 reply_count 记在 A 帖、
--       comment_count 记在 B 帖，计数器会写出无法解释的数据
--   (c) 回复的 root_id 必须等于父评论所在的楼 —— 防止把回复挂到别的楼下
--
-- 做法：生成列 effective_root_id = COALESCE(root_id, id)，
-- 即「这一行属于哪个楼」（根评论属于自己那一楼）。
-- 外键 (parent_id, post_id, root_id) → (id, post_id, effective_root_id)：
--   · 根评论两列皆 NULL → MATCH SIMPLE 跳过检查
--   · 回复 root  评论 R：要求存在 (R.id, 同帖, R.id)      —— R 的 effective_root 就是自己 ✓
--   · 回复非 root 评论 C：要求存在 (C.id, 同帖, C.root_id) —— 楼号必须与 C 一致 ✓
CREATE TABLE comments (
    id               bigint      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    post_id          bigint      NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    author_id        bigint      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    parent_id        bigint,
    root_id          bigint,
    -- 「回复某人」不能随便填：楼主评论指向帖子作者，回复指向父评论作者。
    -- 这个字段影响渲染（「回复 张三：」）与通知投递，填错就是可见的错误状态。
    -- 用复合外键锚定，不依赖服务层自觉——见表末尾两条 fk_comments_reply_to_*。
    reply_to_user_id bigint      NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    content          text        NOT NULL,
    like_count       integer     NOT NULL DEFAULT 0,
    reply_count      integer     NOT NULL DEFAULT 0,
    -- 软删除：删一条评论不能连带毁掉挂在它下面的别人的回复，
    -- 因此删除只打标记、保留行；公开查询整条过滤，不渲染占位。
    -- content 不清空，管理员复核时要能看到原文。
    deleted_at       timestamptz,
    deleted_reason   varchar(16),
    deleted_by       bigint      REFERENCES users (id) ON DELETE RESTRICT,
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now(),

    -- 「这一行属于哪个楼」：根评论是自己，回复是它的 root
    effective_root_id bigint GENERATED ALWAYS AS (COALESCE(root_id, id)) STORED,
    -- 仅楼主评论有值，用于把 reply_to_user_id 锚定到帖子作者；回复行为 NULL 时复合外键跳过
    root_post_id_for_author_check bigint GENERATED ALWAYS AS
        (CASE WHEN parent_id IS NULL THEN post_id ELSE NULL END) STORED,

    CONSTRAINT comments_not_self_parent_check CHECK (parent_id IS DISTINCT FROM id),
    CONSTRAINT comments_not_self_root_check   CHECK (root_id   IS DISTINCT FROM id),
    -- 三者成组：未删除时不得残留删除信息，已删除时来源必填
    CONSTRAINT comments_delete_pair_check CHECK (
        CASE WHEN deleted_at IS NULL
             THEN deleted_reason IS NULL AND deleted_by IS NULL
             ELSE deleted_reason IS NOT NULL
        END
    ),
    CONSTRAINT comments_delete_reason_check
        CHECK (deleted_reason IS NULL OR deleted_reason IN ('author', 'admin', 'moderation')),
    CONSTRAINT comments_root_pair_check       CHECK ((parent_id IS NULL) = (root_id IS NULL)),
    CONSTRAINT comments_counters_check        CHECK (like_count >= 0 AND reply_count >= 0),
    -- reply_count 只在楼主评论上有意义（整层楼的回复数），回复行恒为 0
    CONSTRAINT comments_reply_count_root_only_check
        CHECK (root_id IS NULL OR reply_count = 0),

    -- 被下方复合外键引用，PostgreSQL 要求引用目标列组有唯一约束
    CONSTRAINT uq_comments_id_post_root UNIQUE (id, post_id, effective_root_id),
    CONSTRAINT fk_comments_parent
        FOREIGN KEY (parent_id, post_id, root_id)
        REFERENCES comments (id, post_id, effective_root_id) ON DELETE CASCADE,

    -- 楼主评论（parent_id 为空）：reply_to_user_id 必须是帖子作者。
    -- 生成列在无父时回填 post_id，有父时为 NULL，让 MATCH SIMPLE 只在楼主评论上生效。
    CONSTRAINT fk_comments_reply_to_post_author
        FOREIGN KEY (root_post_id_for_author_check, reply_to_user_id)
        REFERENCES posts (id, author_id) ON DELETE RESTRICT,
    -- 回复：reply_to_user_id 必须是父评论作者
    CONSTRAINT fk_comments_reply_to_parent_author
        FOREIGN KEY (parent_id, reply_to_user_id)
        REFERENCES comments (id, author_id) ON DELETE RESTRICT,
    CONSTRAINT uq_comments_id_author UNIQUE (id, author_id)
);

-- 取某帖的楼主评论列表
CREATE INDEX idx_comments_post_roots ON comments (post_id, created_at DESC)
    WHERE root_id IS NULL;
-- 取某一楼的全部回复（拍扁呈现用，按时间正序）
CREATE INDEX idx_comments_root_created ON comments (root_id, created_at)
    WHERE root_id IS NOT NULL;
-- 管理端复核被机审删掉的评论
CREATE INDEX idx_comments_deleted ON comments (deleted_at DESC)
    WHERE deleted_at IS NOT NULL;

CREATE TRIGGER trg_comments_forbid_delete
    BEFORE DELETE ON comments
    FOR EACH ROW EXECUTE FUNCTION danshi_forbid_hard_delete();
CREATE INDEX idx_comments_post_created ON comments (post_id, created_at DESC);
CREATE INDEX idx_comments_parent       ON comments (parent_id) WHERE parent_id IS NOT NULL;
CREATE INDEX idx_comments_author       ON comments (author_id);

COMMENT ON TABLE comments IS
  '评论。存储保留真实回复链（parent_id 可任意深），展示按 root_id 拍扁成两层。'
  '同帖、楼号一致两条不变式由 fk_comments_parent 复合外键保证。';
COMMENT ON COLUMN comments.parent_id IS
  '直接回复的那条评论。为空表示这是楼主评论（用户点的是帖子的评论按钮）。'
  '与 root_id 同时为空或同时非空。';
COMMENT ON COLUMN comments.root_id IS
  '所属楼的楼主评论 id。为空表示自己就是楼主评论。'
  '回复楼主评论时 root_id = parent_id；回复楼内其他评论时 root_id = 该评论的 root_id。'
  '前端按此列分组即可拍扁呈现，不需要递归。';
COMMENT ON COLUMN comments.effective_root_id IS
  '生成列 COALESCE(root_id, id)：这一行属于哪个楼。仅用于支撑 fk_comments_parent，'
  '业务代码不必读它。';
COMMENT ON COLUMN comments.reply_to_user_id IS
  '「回复 @某人」中被回复的那一个人，用于渲染「回复 张三：」前缀与投递通知。'
  '**取值由结构决定，不接受客户端自由指定**：楼主评论必须是帖子作者，回复必须是父评论作者，'
  '两条复合外键强制。与 comment_mentions 是两回事：这是回复对象，那是正文里 @ 到的人。';
COMMENT ON COLUMN comments.reply_count IS
  '整层楼**未删除**的回复总数（按 root_id 统计，不是直接子节点数），由触发器维护，应用层禁止直接写。'
  '回复行上恒为 0，见 comments_reply_count_root_only_check。';
COMMENT ON COLUMN comments.deleted_at IS
  '软删除标记。非空行不进入公开评论响应，行保留以维系回复链和管理员复核。'
  '不计入 posts.comment_count 与楼主的 reply_count。'
  '物理删除被 trg_comments_forbid_delete 拒绝——帖子与用户现在也都是软删除，'
  '不存在「删帖/注销顺带硬删评论」这条路径了。';
COMMENT ON COLUMN comments.deleted_reason IS
  'author 作者自己删；admin 管理员删；moderation 机器审核判定违规自动删。'
  '区分来源是为了让管理端能筛出机审误杀并恢复。';


-- ============================================================
-- comment_mentions：取代 comments.mentioned_user_ids JSONB
-- ============================================================

CREATE TABLE comment_mentions (
    comment_id bigint NOT NULL REFERENCES comments (id) ON DELETE CASCADE,
    user_id    bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,

    PRIMARY KEY (comment_id, user_id)
);

CREATE INDEX idx_comment_mentions_user ON comment_mentions (user_id);

COMMENT ON TABLE comment_mentions IS
  '评论正文中 @ 到的用户，用于推送提及通知。旧库存裸 uuid 数组无外键，'
  '用户注销后会留下指向不存在用户的悬挂 id。';


-- ============================================================
-- follows / favorites
-- ============================================================

CREATE TABLE follows (
    follower_id  bigint      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    following_id bigint      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at   timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (follower_id, following_id),
    CONSTRAINT follows_no_self_check CHECK (follower_id <> following_id)
);

CREATE INDEX idx_follows_following ON follows (following_id);

COMMENT ON TABLE  follows IS '单向关注。互关由两行表达，不设独立状态。';
COMMENT ON COLUMN follows.following_id IS '被关注者。反向索引支撑「谁关注了我」的粉丝列表。';

CREATE TABLE favorites (
    user_id    bigint      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    post_id    bigint      NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (user_id, post_id)
);

CREATE INDEX idx_favorites_post ON favorites (post_id);

COMMENT ON TABLE favorites IS '收藏（私有书签），与点赞是两个独立动作：点赞公开计数，收藏只有自己看得到。';


-- ============================================================
-- post_likes / comment_likes：取代多态 likes 表
-- ============================================================

CREATE TABLE post_likes (
    user_id    bigint      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    post_id    bigint      NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (user_id, post_id)
);

CREATE INDEX idx_post_likes_post ON post_likes (post_id);

CREATE TABLE comment_likes (
    user_id    bigint      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    comment_id bigint      NOT NULL REFERENCES comments (id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (user_id, comment_id)
);

CREATE INDEX idx_comment_likes_comment ON comment_likes (comment_id);

COMMENT ON TABLE comment_likes IS
  '评论点赞。与 post_likes 同为旧多态 likes 表拆分而来。';
COMMENT ON TABLE post_likes IS
  '旧库用单张多态 likes 表（likeable_type + 裸 uuid likeable_id，无外键），'
  '删除评论不会级联删除其点赞，会留下悬挂行。拆表后由外键保证。';


-- ============================================================
-- notifications
-- ============================================================

CREATE TABLE notifications (
    id                 bigint      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    recipient_id       bigint      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    sender_id          bigint      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    type               varchar(20) NOT NULL,
    -- 旧库是 related_id(裸 uuid) + related_type，无外键，实测已有 2 条悬挂通知。
    related_post_id    bigint      REFERENCES posts (id) ON DELETE CASCADE,
    related_comment_id bigint      REFERENCES comments (id) ON DELETE CASCADE,
    content            varchar(100),
    is_read            boolean     NOT NULL DEFAULT false,
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT notifications_type_check
        CHECK (type IN ('like_post', 'like_comment', 'comment', 'reply', 'mention', 'follow')),
    -- 关联目标由 type 唯一决定，比「至多一个」更严：
    --   like_post / comment            → 只能关联帖子
    --   like_comment / reply / mention → 只能关联评论
    --   follow                         → 两者都必须为空
    CONSTRAINT notifications_target_matches_type_check CHECK (
        CASE type
            WHEN 'like_post'    THEN related_post_id IS NOT NULL AND related_comment_id IS NULL
            WHEN 'comment'      THEN related_post_id IS NOT NULL AND related_comment_id IS NULL
            WHEN 'like_comment' THEN related_comment_id IS NOT NULL AND related_post_id IS NULL
            WHEN 'reply'        THEN related_comment_id IS NOT NULL AND related_post_id IS NULL
            WHEN 'mention'      THEN related_comment_id IS NOT NULL AND related_post_id IS NULL
            WHEN 'follow'       THEN related_post_id IS NULL AND related_comment_id IS NULL
        END
    ),
    -- 正文预览只属于「有话可引」的三类通知；点赞与关注不该带预览。
    -- PRD 的通知表把这一列写死了有无，数据库就该守住，否则前端渲染会出现空预览框。
    CONSTRAINT notifications_content_matches_type_check CHECK (
        CASE WHEN type IN ('comment', 'reply', 'mention')
             THEN content IS NOT NULL AND btrim(content) <> ''
             ELSE content IS NULL
        END
    )
);

CREATE INDEX idx_notifications_recipient_created ON notifications (recipient_id, created_at DESC);
CREATE INDEX idx_notifications_recipient_unread  ON notifications (recipient_id)
    WHERE is_read = false;

COMMENT ON TABLE notifications IS
  '站内通知。关联目标由 type 唯一决定（notifications_target_matches_type_check），'
  '不再是旧库那种「related_type 字符串 + 裸 related_id」的松散组合。';
COMMENT ON COLUMN notifications.type IS
  'like_post 赞了你的帖子；like_comment 赞了你的评论；comment 评论了你的帖子；'
  'reply 回复了你的评论；mention 在评论里 @ 了你；follow 关注了你。';
COMMENT ON COLUMN notifications.content IS
  '评论正文预览，Python 侧取前 100 字符（comment / reply / mention 三类会写入，'
  '点赞与关注为 NULL）。前端 notification_item.tsx 按 type 渲染这段预览，是活字段。';
COMMENT ON COLUMN notifications.sender_id IS '触发通知的人。系统通知暂无此类型，故为 NOT NULL。';
COMMENT ON COLUMN notifications.related_post_id IS
  'API 仍对外输出 related_id / related_type，由本列与 related_comment_id 推导，契约不变。';


-- ============================================================
-- email_verification_codes
-- ============================================================

CREATE TABLE email_verification_codes (
    id                    bigint      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email                 varchar(255) NOT NULL,
    purpose               varchar(32) NOT NULL DEFAULT 'registration',
    code_digest           varchar(64) NOT NULL,
    expires_at            timestamptz NOT NULL,
    last_sent_at          timestamptz,
    send_window_started_at timestamptz NOT NULL,
    send_count            integer     NOT NULL DEFAULT 0,
    failed_attempts       integer     NOT NULL DEFAULT 0,
    consumed_at           timestamptz,
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT evc_counters_check CHECK (send_count >= 0 AND failed_attempts >= 0)
);

CREATE UNIQUE INDEX uq_evc_email_purpose ON email_verification_codes (lower(email), purpose);
CREATE INDEX idx_evc_expires_at ON email_verification_codes (expires_at);

COMMENT ON TABLE email_verification_codes IS
  '邮箱验证码。每个 (邮箱, 用途) 只保留一行，重发覆盖同一行而非追加。';
COMMENT ON COLUMN email_verification_codes.purpose IS 'registration 注册验证。预留其他用途如找回密码。';
COMMENT ON COLUMN email_verification_codes.code_digest IS '验证码摘要，明文不落库。';
COMMENT ON COLUMN email_verification_codes.send_window_started_at IS
  '发送频率窗口起点，与 send_count 一起限制「单位时间内最多发几次」；窗口过期后重置。';
COMMENT ON COLUMN email_verification_codes.last_sent_at IS '上次发送时刻，用于两次发送之间的最小间隔。';
COMMENT ON COLUMN email_verification_codes.failed_attempts IS '连续校验失败次数，超限后作废该码防爆破。';
COMMENT ON COLUMN email_verification_codes.consumed_at IS '已使用则非空；非空的码不可再次校验通过。';


-- ============================================================
-- user_sessions：会话表，令牌撤销的唯一真源
--
-- 旧实现的 /auth/logout 是个空壳（源码注释自陈「jwt 无状态，无需禁用 token」），
-- 只有前端删掉本地存储，token 本身在服务端仍然有效直到过期——refresh 最长 30 天。
--
-- 新模型：**access token 与 refresh token 都绑定到一条会话行，两者都不是无状态的**。
-- 一行 = 一台设备的一次登录。
--
--   access  { sub, sid, iat, exp, type:"access"  }
--   refresh { sub, sid, iat, exp, type:"refresh" }
--
-- 每个需要鉴权的请求都按 sid 查本表：
--   命中且 revoked_at IS NULL 且未过期 → 放行；否则 401。
-- 因此撤销**一律立即生效**，没有「access token 还能再用一会儿」的窗口：
--   本设备登出   → 撤销该行
--   登出所有设备 → 撤销该用户全部行
--   踢掉某设备   → 撤销那一行
-- 不需要额外的版本号、黑名单或撤销时序表。
--
-- 成本：每请求多一次主键查找。鉴权本来就要查 users，实现上与 users 一次 JOIN 取回即可，
-- 不增加往返次数。
--
-- refresh token 在会话生命周期内不轮转：摘要固定，撤销才是安全机制。
-- 不做轮转就没有「弱网重试被误判为重放」的问题，也不需要宽限窗口。
-- 代价是 refresh token 若泄露，攻击者可在会话有效期内冒用——
-- 对应的处置手段是用户在「我的登录设备」里看到陌生设备并踢掉。
-- ============================================================

CREATE TABLE user_sessions (
    id                    bigint      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id               bigint      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    refresh_token_digest  char(64)    NOT NULL,
    device_label          varchar(100),
    user_agent            varchar(512),
    -- IP 用 varchar 而非 inet：只用于展示，不做网段运算，
    -- 且 inet 在 GORM/pgx 侧需要自定义类型，不值得为此增加摩擦。45 字符可容纳 IPv6。
    ip                    varchar(45),
    created_at            timestamptz NOT NULL DEFAULT now(),
    last_seen_at          timestamptz NOT NULL DEFAULT now(),
    expires_at            timestamptz NOT NULL,
    revoked_at            timestamptz,

    -- 摘要是 sha256 十六进制；char(64) 已限长，此约束排除大写与非法字符
    CONSTRAINT user_sessions_digest_format_check
        CHECK (refresh_token_digest ~ '^[0-9a-f]{64}$'),
    -- 时间顺序：过期必须晚于创建，活跃与撤销不能早于创建
    CONSTRAINT user_sessions_expires_after_created_check CHECK (expires_at   > created_at),
    CONSTRAINT user_sessions_seen_after_created_check    CHECK (last_seen_at >= created_at),
    CONSTRAINT user_sessions_revoked_after_created_check
        CHECK (revoked_at IS NULL OR revoked_at >= created_at),
    -- 会话过期或撤销之后不可能再有活跃记录
    CONSTRAINT user_sessions_seen_before_expires_check CHECK (last_seen_at <= expires_at),
    CONSTRAINT user_sessions_seen_before_revoked_check
        CHECK (revoked_at IS NULL OR last_seen_at <= revoked_at)
);

CREATE UNIQUE INDEX uq_user_sessions_digest ON user_sessions (refresh_token_digest);
-- 「我的登录设备」列表：只看仍然有效的会话
CREATE INDEX idx_user_sessions_active ON user_sessions (user_id, last_seen_at DESC)
    WHERE revoked_at IS NULL;
-- 过期会话清理任务
CREATE INDEX idx_user_sessions_expires ON user_sessions (expires_at)
    WHERE revoked_at IS NULL;

COMMENT ON TABLE user_sessions IS
  '一行 = 一台设备的一次登录，是令牌是否有效的唯一真源。'
  'refresh token 只存 sha256 摘要，明文不落库——数据库泄露不等于会话可被冒用。';
COMMENT ON COLUMN user_sessions.refresh_token_digest IS
  '该会话 refresh token 的 sha256 十六进制摘要。会话存续期间不变（不做轮转）。';
COMMENT ON COLUMN user_sessions.device_label IS
  '设备名，可由用户命名或从 User-Agent 解析。用于「我的登录设备」列表展示与识别陌生登录。';
COMMENT ON COLUMN user_sessions.last_seen_at IS
  '最后活跃时刻。⚠ 不要每个请求都写，否则每次鉴权都变成一次写事务；'
  '应用层应设节流阈值（如距上次超过 5 分钟才更新）。';
COMMENT ON COLUMN user_sessions.expires_at IS
  '会话绝对过期时间（登录时 + JWT_REFRESH_EXPIRE_DAYS）。到期必须重新登录。';
COMMENT ON COLUMN user_sessions.revoked_at IS
  '非空即失效，鉴权立刻拒绝。行不物理删除，保留供安全审计与「最近登出记录」展示。';


-- ============================================================
-- post_histories / comment_histories：编辑历史快照
--
-- 帖子与评论都可以编辑。当前内容始终只保存在主表，历史表只保存被替换的旧版本：
--   创建 → 不写历史，当前版本号为 1
--   首次编辑 → 旧内容写 revision 1，新内容留在主表且当前版本号为 2
-- 因此历史 revision N 就是第 N 版内容，当前版本号 = 最大历史 revision + 1。
-- 00015 用 moderation_records.content_revision 直接记录被审版本号，不把尚在主表里的
-- 当前内容重复写入历史表，也不要求审核流水外键指向当时尚不存在的历史行。
--
-- 用途：申诉与追责（「他改之前写的是什么」）、机审复核、以及编辑滥用排查
-- （发一条正常内容过审后再改成违规内容，是内容平台的经典绕过手法——
--  有了快照，机审可以对每个新版本重新跑，管理员也能看到改动轨迹）。
--
-- 帖子的可编辑字段跨了 posts、post_tags、post_flavors、post_images 四张表，
-- 用 jsonb 整体快照而不是逐列建镜像表：快照是只读的历史证据，不参与查询与外键，
-- 逐列建表既繁琐又会在 schema 演进时产生两套需要同步维护的定义。
-- ============================================================

CREATE TABLE post_histories (
    id          bigint      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    post_id     bigint      NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    revision    integer     NOT NULL,
    edited_by   bigint      NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    edited_at   timestamptz NOT NULL DEFAULT now(),
    -- 该版本的完整内容快照
    snapshot    jsonb       NOT NULL,
    edit_reason varchar(200),

    CONSTRAINT post_histories_snapshot_object_check
        CHECK (jsonb_typeof(snapshot) = 'object'),
    CONSTRAINT post_histories_revision_check CHECK (revision >= 1),
    CONSTRAINT uq_post_histories_revision UNIQUE (post_id, revision),
    -- 供 moderation_records 的复合外键引用：审核记录必须指向**同一个帖子**的版本
    CONSTRAINT uq_post_histories_id_post UNIQUE (id, post_id)
);

CREATE INDEX idx_post_histories_post ON post_histories (post_id, edited_at DESC);
CREATE INDEX idx_post_histories_editor ON post_histories (edited_by, edited_at DESC);

-- 编辑历史是追加不可篡改的：改快照等于伪造证据，删快照等于销毁证据。
-- DELETE 复用 danshi_forbid_hard_delete，因此运维物理清除帖子时（开逃生阀）能正常级联。
CREATE TRIGGER trg_post_histories_immutable
    BEFORE UPDATE ON post_histories
    FOR EACH ROW EXECUTE FUNCTION danshi_forbid_row_update();
CREATE TRIGGER trg_post_histories_forbid_delete
    BEFORE DELETE ON post_histories
    FOR EACH ROW EXECUTE FUNCTION danshi_forbid_hard_delete();

COMMENT ON TABLE post_histories IS
  '帖子的**全量版本表**。创建写 revision 1，每次编辑追加一版并把主表同步为该版内容，'
  '因此「主表 == 最新一条历史」。追加不可篡改，不参与业务查询。';
COMMENT ON COLUMN post_histories.revision IS
  '版本号，从 1 起单调递增。moderation_records 用 (post_id, post_history_id) 复合外键'
  '锚定「这条审核结论审的是哪一版」。';
COMMENT ON COLUMN post_histories.snapshot IS
  '编辑前的完整内容，至少包含 title / content / category / share_type / price / '
  'budget_min / budget_max / canteen_id / canteen_window_id / cuisine_id / '
  'tags / flavors / images（后三者展开为名称或 id 数组）。'
  '用 jsonb 是因为可编辑字段跨四张表，且快照是历史证据而非查询对象。';
COMMENT ON COLUMN post_histories.edited_by IS
  '执行编辑的人。通常是作者，管理员代为修改时记管理员。外键用 RESTRICT，留痕不可丢。';

CREATE TABLE comment_histories (
    id         bigint      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    comment_id bigint      NOT NULL REFERENCES comments (id) ON DELETE CASCADE,
    revision   integer     NOT NULL,
    edited_by  bigint      NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    edited_at  timestamptz NOT NULL DEFAULT now(),
    -- 评论可编辑内容只有正文，不必用 jsonb
    content    text        NOT NULL,

    CONSTRAINT comment_histories_revision_check CHECK (revision >= 1),
    CONSTRAINT uq_comment_histories_revision UNIQUE (comment_id, revision),
    CONSTRAINT uq_comment_histories_id_comment UNIQUE (id, comment_id)
);

CREATE INDEX idx_comment_histories_comment ON comment_histories (comment_id, edited_at DESC);
CREATE INDEX idx_comment_histories_editor  ON comment_histories (edited_by, edited_at DESC);

CREATE TRIGGER trg_comment_histories_immutable
    BEFORE UPDATE ON comment_histories
    FOR EACH ROW EXECUTE FUNCTION danshi_forbid_row_update();
CREATE TRIGGER trg_comment_histories_forbid_delete
    BEFORE DELETE ON comment_histories
    FOR EACH ROW EXECUTE FUNCTION danshi_forbid_hard_delete();

COMMENT ON TABLE comment_histories IS
  '评论的全量版本表，语义同 post_histories：创建写 revision 1，每次编辑追加一版。';


-- ============================================================
-- moderation_records：内容审核流水
--
-- 审核范围：**一切用户可输入的内容**——帖子标题与正文、评论正文、话题标签、
-- 用户昵称与个人简介、以及所有上传的图片。
--
-- 时序分两类：
--   帖子   **先审后发**：提交后停在 pending，机审通过才 approved；
--          机审判需复核则继续停在 pending 等人工裁决（放行或禁止）。
--   其余   **先发后审**：评论、标签、昵称、简介发出即可见，机审异步跟进，
--          判违规则软删除 / 下架，并通知管理员（如飞书机器人）。
--   封闭词表（口味 / 菜系 / 餐厅 / 窗口）不走机审，走 dictionary_suggestions 人工审核。
-- 审核策略（产品口径）：只允许美食与就餐相关内容；违法乱纪、涉政、色情、广告一律拦截。
-- 判定为违规时由管理员决定是否封禁作者（users.banned_until，支持限时）。
--
-- **provider 是可替换的**：后端定义统一的审核接口，腾讯云数据万象只是第一个实现。
-- 本表只记录「谁审的、什么结论、命中什么标签、原始返回是什么」，不绑定任何一家厂商的模型。
-- 换供应商时既有记录仍可读，provider 字段区分来源。
--
-- 结论如何影响内容可见性：
--   帖子   pass → status=approved；review → status=pending 转人工；block → status=rejected
--   评论   pass → 公开；review → 仅作者可见并进入人工复核队列；
--          block → deleted_at 置位、deleted_reason='moderation'、deleted_by 留空，仅作者可见
--   标签   pass → 不动；review → 仍然可用，进人工队列；block → 下架（deleted_at），关联行保留
--   图片   写回 image_assets.moderation；block 不可被引用，pending/review 可先引用，
--          但只要还有图片未 pass，所属帖子就不得进入 approved（§5.2.9）
--   ⚠ review 一律是「保持现状 + 进人工队列」，不是「先删了再说」。
--     五类对象在 PRD §6.10.3 的表里语义一致，不要只对某一类对象特殊处理。
-- ============================================================

CREATE TABLE moderation_records (
    id              bigint      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    -- 审核对象三选一。不用「类型字符串 + 裸 id」的多态写法，那是旧库 likes 表的教训。
    post_id         bigint      REFERENCES posts (id)         ON DELETE CASCADE,
    comment_id      bigint      REFERENCES comments (id)      ON DELETE CASCADE,
    image_asset_id  bigint      REFERENCES image_assets (id)  ON DELETE CASCADE,
    tag_id          bigint      REFERENCES tags (id)          ON DELETE CASCADE,
    -- 用户昵称与个人简介同样是用户输入，同样要审
    user_id         bigint      REFERENCES users (id)         ON DELETE CASCADE,

    -- 帖子与用户有多个可审文本字段，用本列区分审的是哪一段
    field           varchar(32),
    -- 被审内容的版本。复合外键同时锚定「属于哪个对象」，防止指到别的帖子的版本上。
    post_history_id    bigint,
    comment_history_id bigint,

    scene           varchar(16) NOT NULL,
    provider        varchar(32) NOT NULL,
    provider_job_id varchar(128),
    verdict         varchar(16) NOT NULL,
    -- 命中的违规标签。这里用数组而不是字典表：标签取值由外部供应商定义、
    -- 不是用户可见词表、且是一次写入的审计数据，建表没有收益。
    labels          text[]      NOT NULL DEFAULT '{}',
    score           numeric(5,2),
    raw_response    jsonb,
    reviewer_id     bigint      REFERENCES users (id) ON DELETE RESTRICT,
    reviewed_at     timestamptz,
    -- 人工复核不覆盖机审行，而是新插一行 provider='manual' 并用本列指回被复核的机审行
    supersedes_id   bigint      REFERENCES moderation_records (id) ON DELETE RESTRICT,
    created_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT mr_single_target_check
        CHECK (num_nonnulls(post_id, comment_id, image_asset_id, tag_id, user_id) = 1),
    CONSTRAINT mr_scene_check   CHECK (scene IN ('text', 'image')),
    CONSTRAINT mr_verdict_check CHECK (verdict IN ('pass', 'review', 'block')),
    -- 图片只能走图像审核，评论只有文本
    CONSTRAINT mr_scene_target_check
        CHECK (image_asset_id IS NULL OR scene = 'image'),
    CONSTRAINT mr_comment_scene_check
        CHECK (comment_id IS NULL OR scene = 'text'),
    -- 图片是独立的 image_asset 审核对象；其余对象一律只做文本审核
    CONSTRAINT mr_post_scene_check CHECK (post_id IS NULL OR scene = 'text'),
    CONSTRAINT mr_tag_scene_check  CHECK (tag_id  IS NULL OR scene = 'text'),
    CONSTRAINT mr_user_scene_check CHECK (user_id IS NULL OR scene = 'text'),
    -- 用户对象必须指明审的是昵称还是简介
    -- 注意 NULL：field IN (...) 在 field 为 NULL 时求值为 NULL 而非 FALSE，CHECK 会放行，
    -- 所以必须显式加 field IS NOT NULL
    CONSTRAINT mr_user_field_check
        CHECK (user_id IS NULL OR (field IS NOT NULL AND field IN ('name', 'bio'))),
    CONSTRAINT mr_post_field_check
        CHECK (post_id IS NULL OR field IS NULL OR field IN ('title', 'content')),
    -- 版本引用只能出现在对应对象上
    -- 复合外键保证「版本属于这个对象」；但它是 MATCH SIMPLE，
    -- post_id 为 NULL 时会整条跳过，因此仍需下面两条 CHECK 挡住
    -- 「评论的审核记录却带着帖子版本号」这种类型错配。
    CONSTRAINT fk_mr_post_history
        FOREIGN KEY (post_history_id, post_id)
        REFERENCES post_histories (id, post_id) ON DELETE RESTRICT,
    CONSTRAINT fk_mr_comment_history
        FOREIGN KEY (comment_history_id, comment_id)
        REFERENCES comment_histories (id, comment_id) ON DELETE RESTRICT,
    -- 双向成组：帖子/评论的审核结论**必须**指明审的是哪一版，反之版本列也只能出现在对应对象上。
    -- 单向写法（history IS NULL OR 对象 IS NOT NULL）只挡住了「张冠李戴」，
    -- 挡不住「干脆不写版本」，而后者直接违反「每条结论都能回答审的是哪一版」。
    CONSTRAINT mr_post_history_paired_check
        CHECK ((post_id IS NULL) = (post_history_id IS NULL)),
    CONSTRAINT mr_comment_history_paired_check
        CHECK ((comment_id IS NULL) = (comment_history_id IS NULL)),
    CONSTRAINT mr_provider_not_blank_check CHECK (btrim(provider) <> ''),
    CONSTRAINT mr_job_id_not_blank_check
        CHECK (provider_job_id IS NULL OR btrim(provider_job_id) <> ''),
    -- 人工与机器两类记录的字段互斥：人工必须有复核人与时间、不带外部任务号；
    -- 机器记录反之，复核信息一律为空——人工结论要另起一行，不能覆盖机审行。
    CONSTRAINT mr_manual_shape_check CHECK (
        CASE WHEN provider = 'manual'
             THEN reviewer_id IS NOT NULL AND provider_job_id IS NULL
             ELSE reviewer_id IS NULL AND reviewed_at IS NULL
        END
    ),
    CONSTRAINT mr_score_check CHECK (score IS NULL OR (score >= 0 AND score <= 100)),
    -- 人工复核过的必须同时留下人和时间
    CONSTRAINT mr_review_pair_check
        CHECK ((reviewer_id IS NULL) = (reviewed_at IS NULL)),
    CONSTRAINT mr_supersedes_manual_check
        CHECK (supersedes_id IS NULL OR provider = 'manual'),
    CONSTRAINT mr_no_self_supersede_check CHECK (supersedes_id IS DISTINCT FROM id)
);

-- 一条机审记录至多被一条人工记录复核
CREATE UNIQUE INDEX uq_mr_supersedes ON moderation_records (supersedes_id)
    WHERE supersedes_id IS NOT NULL;

CREATE INDEX idx_mr_post    ON moderation_records (post_id, created_at DESC)        WHERE post_id IS NOT NULL;
CREATE INDEX idx_mr_comment ON moderation_records (comment_id, created_at DESC)     WHERE comment_id IS NOT NULL;
CREATE INDEX idx_mr_image   ON moderation_records (image_asset_id, created_at DESC) WHERE image_asset_id IS NOT NULL;
CREATE INDEX idx_mr_tag     ON moderation_records (tag_id, created_at DESC)         WHERE tag_id IS NOT NULL;
CREATE INDEX idx_mr_user    ON moderation_records (user_id, created_at DESC)        WHERE user_id IS NOT NULL;
-- 管理端待复核队列：机审判 review 且尚未被任何人工记录 supersede
-- （是否已被复核需 NOT EXISTS 子查询判定，索引只负责先缩到 review 这一小撮）
CREATE INDEX idx_mr_pending_review ON moderation_records (created_at)
    WHERE verdict = 'review' AND provider <> 'manual';
-- 异步回调按外部任务号对账
CREATE UNIQUE INDEX uq_mr_provider_job ON moderation_records (provider, provider_job_id)
    WHERE provider_job_id IS NOT NULL;
CREATE INDEX idx_mr_labels_gin ON moderation_records USING gin (labels);

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION danshi_forbid_moderation_rewrite()
RETURNS trigger
LANGUAGE plpgsql
AS $func$
BEGIN
  RAISE EXCEPTION
    '审核流水不可覆盖写：人工复核请新插一条 provider=''manual'' 且 supersedes_id 指向机审行的记录'
    USING ERRCODE = 'restrict_violation';
END;
$func$;
-- +goose StatementEnd

-- 「不覆盖写」不能只写在注释里，靠触发器强制。
-- DELETE 同样要挡：删掉审核记录等于销毁追责与申诉的依据。
-- 复用 danshi_forbid_hard_delete，运维物理清除对象时（开逃生阀）仍可级联。
-- 人工复核必须真的「复核那一条机审 review 记录」。
-- 光有「有 supersedes_id 就必须是 manual」远远不够——实测可以写出：
-- manual 行不带 supersedes、复核别的对象的记录、复核 pass 的记录、甚至复核另一条人工行。
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION danshi_check_moderation_review()
RETURNS trigger
LANGUAGE plpgsql
AS $func$
DECLARE t moderation_records%ROWTYPE;
BEGIN
  IF (NEW.provider = 'manual') <> (NEW.supersedes_id IS NOT NULL) THEN
    RAISE EXCEPTION '人工复核记录必须且只能带 supersedes_id，机审记录不得带'
      USING ERRCODE = 'restrict_violation';
  END IF;
  IF NEW.supersedes_id IS NULL THEN
    RETURN NEW;
  END IF;
  SELECT * INTO t FROM moderation_records WHERE id = NEW.supersedes_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION '被复核的审核记录不存在' USING ERRCODE = 'restrict_violation';
  END IF;
  IF t.provider = 'manual' THEN
    RAISE EXCEPTION '不能复核另一条人工复核记录' USING ERRCODE = 'restrict_violation';
  END IF;
  IF t.verdict <> 'review' THEN
    RAISE EXCEPTION '只能复核机审判定为 review 的记录，当前被复核记录 verdict=%', t.verdict
      USING ERRCODE = 'restrict_violation';
  END IF;
  IF (NEW.post_id, NEW.comment_id, NEW.image_asset_id, NEW.tag_id, NEW.user_id,
      NEW.scene, NEW.field, NEW.post_history_id, NEW.comment_history_id)
     IS DISTINCT FROM
     (t.post_id, t.comment_id, t.image_asset_id, t.tag_id, t.user_id,
      t.scene, t.field, t.post_history_id, t.comment_history_id) THEN
    RAISE EXCEPTION '人工复核必须针对同一对象、同一字段、同一版本'
      USING ERRCODE = 'restrict_violation';
  END IF;
  RETURN NEW;
END;
$func$;
-- +goose StatementEnd

CREATE TRIGGER trg_moderation_records_check_review
    BEFORE INSERT ON moderation_records
    FOR EACH ROW EXECUTE FUNCTION danshi_check_moderation_review();

CREATE TRIGGER trg_moderation_records_immutable
    BEFORE UPDATE ON moderation_records
    FOR EACH ROW EXECUTE FUNCTION danshi_forbid_moderation_rewrite();
CREATE TRIGGER trg_moderation_records_forbid_delete
    BEFORE DELETE ON moderation_records
    FOR EACH ROW EXECUTE FUNCTION danshi_forbid_hard_delete();

COMMENT ON TABLE moderation_records IS
  '内容审核流水，一次审核一行，同一对象可以有多行（机审一行、人工复核再一行）。'
  '**行不可修改**（trg_moderation_records_immutable）：人工复核必须新插 provider=''manual'' 的行，'
  '并用 supersedes_id 指回被复核的机审行。审核历史是追责与申诉的依据，必须可回溯。';
COMMENT ON COLUMN moderation_records.supersedes_id IS
  '本条人工复核所针对的机审记录。待复核队列 = 机审 verdict=review 且没有任何行 supersedes 它。';
COMMENT ON COLUMN moderation_records.provider IS
  '审核后端标识，如 tencent_ci（腾讯云数据万象）、manual（人工）。'
  '后端按统一接口抽象，换供应商不影响历史记录的可读性。';
COMMENT ON COLUMN moderation_records.provider_job_id IS
  '外部审核任务号。异步回调按 (provider, provider_job_id) 幂等匹配，重复回调不会写重复行。';
COMMENT ON COLUMN moderation_records.field IS
  '被审的具体字段。用户对象必填（name 昵称 / bio 简介）；帖子可用 title / content 区分，'
  '整体送审时留空。评论、标签、图片各自只有一个可审内容，无需本列。';
COMMENT ON COLUMN moderation_records.post_history_id IS
  '00001 初始模型使用的历史行锚点；00008 删除该列并改为只保存被替换旧版，'
  '00015 再以不带外键的 content_revision 记录被审版本号。';
COMMENT ON COLUMN moderation_records.verdict IS
  'pass 通过；review 需人工复核；block 判定违规。'
  '注意本列是**这一次审核**的结论，对象当前状态看 posts.status / comments.deleted_at / image_assets.moderation。';
COMMENT ON COLUMN moderation_records.labels IS
  '命中的违规标签，如 politics / porn / ad / illegal / off_topic。'
  'off_topic 对应产品口径「只允许美食与就餐相关内容」。';
COMMENT ON COLUMN moderation_records.reviewer_id IS
  '人工复核者。机器审核行此列为空；管理员复核后补写本列与 reviewed_at。';


-- ============================================================
-- dictionary_suggestions：用户提议词条 → 管理员审核 → 入库并回绑帖子
--
-- 口味 / 菜系 / 餐厅 / 窗口是后端写死的受控词表，用户只能选不能填。
-- 但词表不可能一次穷尽（新窗口、新菜系随时出现），所以提供提议通道：
--
--   1. 用户发帖时发现没有合适的词条，提交一条 suggestion（可携带来源帖子 id）
--   2. 管理员在后台看到 pending 列表
--   3. 通过 → 在对应字典表创建条目，回填 resulting_*_id，
--      并按 kind 把新条目绑回 post_id 指向的帖子
--   4. 驳回 → status=rejected，review_note 说明原因
--
-- 一张表覆盖四种词表，靠 kind 区分；resulting_* 用四个可空外键而不是
-- 「一个裸 id + kind」，是为了保住引用完整性（这正是旧库多态 likes 表的教训）。
-- ============================================================

CREATE TABLE dictionary_suggestions (
    id                bigint       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    kind              varchar(20)  NOT NULL,
    proposed_name     varchar(100) NOT NULL,
    -- 审核历史必须留存：用 RESTRICT，避免物理清除用户时连带抹掉其全部提议与审核结论。
    -- 用户注销是软删除，正常路径不会触发本约束。
    proposer_id       bigint       NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    -- 来源帖子。审核通过后把新词条绑回这个帖子；帖子被删则置空，提议本身仍可入库。
    post_id           bigint       REFERENCES posts (id) ON DELETE SET NULL,
    -- kind='flavor' 时必填：新口味绑回帖子时用哪种立场
    flavor_stance     varchar(10),
    -- kind='canteen_window' 时二选一（也可先后都有）：新窗口挂在哪个餐厅下。
    --   parent_canteen_id    —— 挂到一个**已存在**的餐厅
    --   parent_suggestion_id —— 挂到一条同批提交的 kind='canteen' 提议上，
    --                           用于「餐厅和窗口一起提议」：用户发现整个餐厅都没收录时，
    --                           先提餐厅、再提它下面的窗口，两条提议一起进待审列表。
    -- 审核顺序必须是先批餐厅、再批窗口；批窗口时把 parent_canteen_id 补成刚建出的餐厅 id
    -- （ds_parent_canteen_check 要求 approved 时它必须非空），这样下方复合外键才有效。
    parent_canteen_id bigint       REFERENCES canteens (id) ON DELETE RESTRICT,
    parent_suggestion_id bigint,
    -- 生成列：仅用于把 parent_suggestion_id 约束到 kind='canteen' 的提议上
    parent_suggestion_kind varchar(20) GENERATED ALWAYS AS
        (CASE WHEN parent_suggestion_id IS NULL THEN NULL ELSE 'canteen' END) STORED,

    status            varchar(20)  NOT NULL DEFAULT 'pending',
    reviewer_id       bigint       REFERENCES users (id) ON DELETE SET NULL,
    reviewed_at       timestamptz,
    review_note       text,

    -- 通过后指向实际创建（或复用）的字典条目，四选一且必须与 kind 匹配。
    -- 用 RESTRICT 而非 SET NULL：SET NULL 会把 approved 行的产出抹成空，
    -- 直接违反下方 ds_resulting_check，导致管理端删词条时报一个莫名其妙的约束错误。
    -- 语义上也应该是「被审核历史引用的词条不能物理删除，只能 is_active=false」。
    resulting_flavor_id  bigint REFERENCES flavors (id)         ON DELETE RESTRICT,
    resulting_cuisine_id bigint REFERENCES cuisines (id)        ON DELETE RESTRICT,
    resulting_canteen_id bigint REFERENCES canteens (id)        ON DELETE RESTRICT,
    resulting_window_id  bigint,

    created_at        timestamptz  NOT NULL DEFAULT now(),
    updated_at        timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT ds_kind_check   CHECK (kind IN ('flavor', 'cuisine', 'canteen', 'canteen_window')),
    CONSTRAINT ds_status_check CHECK (status IN ('pending', 'approved', 'rejected')),
    CONSTRAINT ds_name_trimmed_check
        CHECK (proposed_name = btrim(proposed_name) AND btrim(proposed_name) <> ''),

    -- kind 决定哪些辅助字段必填
    CONSTRAINT ds_flavor_stance_check
        CHECK ((kind = 'flavor') = (flavor_stance IS NOT NULL)),
    CONSTRAINT ds_flavor_stance_enum_check
        CHECK (flavor_stance IS NULL OR flavor_stance IN ('has', 'prefer', 'avoid')),
    -- 窗口提议必须指明父餐厅：已存在的餐厅、或同批提交的餐厅提议，至少有一个。
    -- 审核通过时 parent_canteen_id 必须已落实（否则 fk_ds_resulting_window 形同虚设）。
    CONSTRAINT ds_parent_canteen_check CHECK (
        CASE WHEN kind = 'canteen_window'
             THEN num_nonnulls(parent_canteen_id, parent_suggestion_id) >= 1
                  AND (status <> 'approved' OR parent_canteen_id IS NOT NULL)
             ELSE parent_canteen_id IS NULL AND parent_suggestion_id IS NULL
        END
    ),
    CONSTRAINT ds_no_self_parent_check CHECK (parent_suggestion_id IS DISTINCT FROM id),
    -- 父提议必须是一条餐厅提议，不能把窗口挂到口味/菜系提议上
    CONSTRAINT uq_ds_id_kind UNIQUE (id, kind),
    CONSTRAINT fk_ds_parent_suggestion
        FOREIGN KEY (parent_suggestion_id, parent_suggestion_kind)
        REFERENCES dictionary_suggestions (id, kind) ON DELETE RESTRICT,
    -- 光约束「父提议是餐厅提议」还不够：曾经可以写出「窗口提议挂在 A 餐厅提议上，
    -- 却把窗口批到 B 餐厅」的错配状态，以及「父提议还是 pending 就先批了子提议」。
    -- 下面这条复合外键把两个洞一起堵上：
    --   parent_canteen_id 必须等于父提议实际批出来的那个餐厅。
    --   父提议未批准时 resulting_canteen_id 为空，配不上任何非空值 ⇒ 子提议批不了。
    --   pending 阶段子提议的 parent_canteen_id 为空 ⇒ MATCH SIMPLE 跳过，不妨碍先提交。
    CONSTRAINT uq_ds_id_resulting_canteen UNIQUE (id, resulting_canteen_id),
    CONSTRAINT fk_ds_parent_resulting_canteen
        FOREIGN KEY (parent_suggestion_id, parent_canteen_id)
        REFERENCES dictionary_suggestions (id, resulting_canteen_id) ON DELETE RESTRICT,
    -- 批出来的窗口必须真的挂在提议时指定的那个餐厅下
    CONSTRAINT fk_ds_resulting_window
        FOREIGN KEY (resulting_window_id, parent_canteen_id)
        REFERENCES canteen_windows (id, canteen_id) ON DELETE RESTRICT,

    -- pending：审核人与时间都必须为空；approved/rejected：两者都必须有值。
    -- 写成等式 `(status='pending') = (reviewer_id IS NULL AND reviewed_at IS NULL)` 是不够的——
    -- 那样非 pending 时只要求「不同时为空」，可以只有审核人没有时间。
    CONSTRAINT ds_review_fields_check CHECK (
        CASE WHEN status = 'pending'
             THEN reviewer_id IS NULL     AND reviewed_at IS NULL
             ELSE reviewer_id IS NOT NULL AND reviewed_at IS NOT NULL
        END
    ),
    -- 驳回必须说明理由
    CONSTRAINT ds_reject_note_check
        CHECK (status <> 'rejected' OR btrim(coalesce(review_note, '')) <> ''),

    -- 只有 approved 才有产出，且产出类型必须与 kind 对应
    CONSTRAINT ds_resulting_check CHECK (
        CASE WHEN status = 'approved' THEN
            num_nonnulls(resulting_flavor_id, resulting_cuisine_id,
                         resulting_canteen_id, resulting_window_id) = 1
            AND (kind <> 'flavor'         OR resulting_flavor_id  IS NOT NULL)
            AND (kind <> 'cuisine'        OR resulting_cuisine_id IS NOT NULL)
            AND (kind <> 'canteen'        OR resulting_canteen_id IS NOT NULL)
            AND (kind <> 'canteen_window' OR resulting_window_id  IS NOT NULL)
        ELSE
            num_nonnulls(resulting_flavor_id, resulting_cuisine_id,
                         resulting_canteen_id, resulting_window_id) = 0
        END
    )
);

-- 管理端待办列表：按 kind 分组、按提交时间正序处理
CREATE INDEX idx_ds_pending ON dictionary_suggestions (kind, created_at)
    WHERE status = 'pending';
CREATE INDEX idx_ds_proposer ON dictionary_suggestions (proposer_id, created_at DESC);

-- 提议与审核结论要永久保留：既不能删，也不能把已经批准/驳回的行改回 pending、
-- 或事后篡改提议名与产出。实测这两条路原先都是通的。
CREATE TRIGGER trg_ds_forbid_delete
    BEFORE DELETE ON dictionary_suggestions
    FOR EACH ROW EXECUTE FUNCTION danshi_forbid_hard_delete();

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION danshi_check_suggestion_transition()
RETURNS trigger
LANGUAGE plpgsql
AS $func$
BEGIN
  IF OLD.status <> 'pending' THEN
    IF NEW.status <> OLD.status THEN
      RAISE EXCEPTION '提议已是终态 %，不可再变更为 %；需要改判请另建提议',
        OLD.status, NEW.status USING ERRCODE = 'restrict_violation';
    END IF;
    -- 终态冻结**全部**业务与审计字段，不只是审核结论与产出。
    -- 早先漏掉 post_id / flavor_stance / 父提议 / 父餐厅 / created_at，
    -- 结果可以把一条已批准的提议改绑到另一篇帖子、改掉已审过的口味立场。
    IF (NEW.kind, NEW.proposed_name, NEW.proposer_id, NEW.reviewer_id, NEW.reviewed_at,
        NEW.review_note, NEW.resulting_flavor_id, NEW.resulting_cuisine_id,
        NEW.resulting_canteen_id, NEW.resulting_window_id,
        NEW.flavor_stance, NEW.parent_canteen_id, NEW.parent_suggestion_id, NEW.created_at)
       IS DISTINCT FROM
       (OLD.kind, OLD.proposed_name, OLD.proposer_id, OLD.reviewer_id, OLD.reviewed_at,
        OLD.review_note, OLD.resulting_flavor_id, OLD.resulting_cuisine_id,
        OLD.resulting_canteen_id, OLD.resulting_window_id,
        OLD.flavor_stance, OLD.parent_canteen_id, OLD.parent_suggestion_id, OLD.created_at) THEN
      RAISE EXCEPTION '终态提议的内容、审核结论与产出均不可篡改' USING ERRCODE = 'restrict_violation';
    END IF;
    -- post_id 例外：来源帖被物理清除时 ON DELETE SET NULL 会把它置空，这是合法的；
    -- 但不允许改绑到另一篇帖子。
    IF NEW.post_id IS DISTINCT FROM OLD.post_id AND NEW.post_id IS NOT NULL THEN
      RAISE EXCEPTION '终态提议不可改绑来源帖子' USING ERRCODE = 'restrict_violation';
    END IF;
  END IF;
  RETURN NEW;
END;
$func$;
-- +goose StatementEnd

CREATE TRIGGER trg_ds_transition
    BEFORE UPDATE ON dictionary_suggestions
    FOR EACH ROW EXECUTE FUNCTION danshi_check_suggestion_transition();
CREATE INDEX idx_ds_post     ON dictionary_suggestions (post_id) WHERE post_id IS NOT NULL;

COMMENT ON TABLE dictionary_suggestions IS
  '用户提议的词表条目。刻意**不加**「同名 pending 唯一」约束：'
  '多个用户可能为各自的帖子提议同一个词，每条提议都要保留自己的 post_id 才能分别回绑。'
  '管理端负责聚合展示同名提议，通过时让它们的 resulting_*_id 指向同一个字典条目。';
COMMENT ON COLUMN dictionary_suggestions.kind IS
  'flavor 口味 / cuisine 菜系 / canteen 餐厅 / canteen_window 窗口。'
  'tags 不走此流程——标签本就允许用户自由创建。';
COMMENT ON COLUMN dictionary_suggestions.post_id IS
  '触发这次提议的帖子。审核通过后按 kind 把新词条写回该帖：'
  'flavor → post_flavors(stance)；cuisine → posts.cuisine_id；'
  'canteen → posts.canteen_id；canteen_window → posts.canteen_window_id(+canteen_id)。';
COMMENT ON COLUMN dictionary_suggestions.flavor_stance IS
  '仅 kind=flavor 时有值，决定回绑到帖子时写入 post_flavors.stance 的哪一种。';
COMMENT ON COLUMN dictionary_suggestions.parent_canteen_id IS
  '仅 kind=canteen_window 时使用：新窗口挂在哪个**已存在**的餐厅下。'
  '若餐厅本身也是新提议的，提交时此列为空、改填 parent_suggestion_id，'
  '待餐厅提议批准后再回填本列——ds_parent_canteen_check 要求 approved 时它必须非空。';
COMMENT ON COLUMN dictionary_suggestions.parent_suggestion_id IS
  '「餐厅和窗口一起提议」的场景：整个餐厅都没收录时，用户先提餐厅、再提它下面的窗口，'
  '窗口提议用本列指向那条餐厅提议。'
  '两条复合外键联合保证：父提议必须是 kind=canteen；批窗口时 parent_canteen_id 必须等于'
  '父提议实际批出来的餐厅，因此父提议未批准（resulting_canteen_id 为空）时子提议根本批不了——'
  '「先批餐厅、再批窗口」这个顺序由数据库强制，不靠管理端自觉。';
CREATE INDEX idx_ds_parent_suggestion ON dictionary_suggestions (parent_suggestion_id)
    WHERE parent_suggestion_id IS NOT NULL;


-- ============================================================
-- 反规范化计数器：由触发器维护
--
-- 旧库由应用层维护，实测 31 篇帖子中 16 篇 like_count 与源表对不上且一律偏低。
-- 计数器是纯机械派生（值就是 COUNT(*)），交给数据库维护才能与源表同事务一致。
--
-- 这些触发器只写计数列，不碰 updated_at——本 schema 已无 updated_at 触发器，
-- 所以点赞、收藏、评论天然不会污染帖子的「内容编辑时间」。
--
-- 同步函数只处理 INSERT / DELETE。若关联键可以被 UPDATE（把一条点赞从帖子 A 改到帖子 B），
-- 两边计数都会永久漂移且无人察觉。因此下面先把这些关联键声明为**不可变**：
-- 需要「换个目标」时必须删除后重建，这样走的仍是 INSERT/DELETE 路径。
-- ============================================================

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION danshi_forbid_key_update()
RETURNS trigger
LANGUAGE plpgsql
AS $func$
BEGIN
  RAISE EXCEPTION
    '% 的关联键不可变更：计数器触发器只处理 INSERT/DELETE，'
    'UPDATE 关联键会让计数器永久漂移。请删除后重建。', TG_TABLE_NAME
    USING ERRCODE = 'restrict_violation';
END;
$func$;
-- +goose StatementEnd

CREATE TRIGGER trg_post_likes_keys_immutable
    BEFORE UPDATE OF user_id, post_id ON post_likes
    FOR EACH ROW
    WHEN (OLD.user_id IS DISTINCT FROM NEW.user_id OR OLD.post_id IS DISTINCT FROM NEW.post_id)
    EXECUTE FUNCTION danshi_forbid_key_update();

CREATE TRIGGER trg_favorites_keys_immutable
    BEFORE UPDATE OF user_id, post_id ON favorites
    FOR EACH ROW
    WHEN (OLD.user_id IS DISTINCT FROM NEW.user_id OR OLD.post_id IS DISTINCT FROM NEW.post_id)
    EXECUTE FUNCTION danshi_forbid_key_update();

CREATE TRIGGER trg_comment_likes_keys_immutable
    BEFORE UPDATE OF user_id, comment_id ON comment_likes
    FOR EACH ROW
    WHEN (OLD.user_id IS DISTINCT FROM NEW.user_id OR OLD.comment_id IS DISTINCT FROM NEW.comment_id)
    EXECUTE FUNCTION danshi_forbid_key_update();

CREATE TRIGGER trg_comments_keys_immutable
    BEFORE UPDATE OF post_id, parent_id, root_id ON comments
    FOR EACH ROW
    WHEN (OLD.post_id   IS DISTINCT FROM NEW.post_id
       OR OLD.parent_id IS DISTINCT FROM NEW.parent_id
       OR OLD.root_id   IS DISTINCT FROM NEW.root_id)
    EXECUTE FUNCTION danshi_forbid_key_update();

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION danshi_sync_post_like_count()
RETURNS trigger
LANGUAGE plpgsql
AS $func$
DECLARE prev text;
BEGIN
  -- 保存并恢复，而不是只置位：set_config 的第三参数是「事务局部」不是「函数局部」，
  -- 只置位会让 GUC 一直留到事务结束，同一个 HTTP 事务里后续任何直接写计数都会被放行。
  prev := current_setting('danshi.allow_counter_write', true);
  PERFORM set_config('danshi.allow_counter_write', 'on', true);
  IF TG_OP = 'INSERT' THEN
    UPDATE posts SET like_count = like_count + 1 WHERE id = NEW.post_id;
    PERFORM set_config('danshi.allow_counter_write', COALESCE(prev, ''), true);
    RETURN NEW;
  END IF;
  UPDATE posts SET like_count = GREATEST(like_count - 1, 0) WHERE id = OLD.post_id;
  PERFORM set_config('danshi.allow_counter_write', COALESCE(prev, ''), true);
  RETURN OLD;
END;
$func$;
-- +goose StatementEnd

CREATE TRIGGER trg_post_likes_sync_count
    AFTER INSERT OR DELETE ON post_likes
    FOR EACH ROW EXECUTE FUNCTION danshi_sync_post_like_count();

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION danshi_sync_post_favorite_count()
RETURNS trigger
LANGUAGE plpgsql
AS $func$
DECLARE prev text;
BEGIN
  -- 保存并恢复，而不是只置位：set_config 的第三参数是「事务局部」不是「函数局部」，
  -- 只置位会让 GUC 一直留到事务结束，同一个 HTTP 事务里后续任何直接写计数都会被放行。
  prev := current_setting('danshi.allow_counter_write', true);
  PERFORM set_config('danshi.allow_counter_write', 'on', true);
  IF TG_OP = 'INSERT' THEN
    UPDATE posts SET favorite_count = favorite_count + 1 WHERE id = NEW.post_id;
    PERFORM set_config('danshi.allow_counter_write', COALESCE(prev, ''), true);
    RETURN NEW;
  END IF;
  UPDATE posts SET favorite_count = GREATEST(favorite_count - 1, 0) WHERE id = OLD.post_id;
  PERFORM set_config('danshi.allow_counter_write', COALESCE(prev, ''), true);
  RETURN OLD;
END;
$func$;
-- +goose StatementEnd

CREATE TRIGGER trg_favorites_sync_count
    AFTER INSERT OR DELETE ON favorites
    FOR EACH ROW EXECUTE FUNCTION danshi_sync_post_favorite_count();

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION danshi_sync_comment_like_count()
RETURNS trigger
LANGUAGE plpgsql
AS $func$
DECLARE prev text;
BEGIN
  -- 保存并恢复，而不是只置位：set_config 的第三参数是「事务局部」不是「函数局部」，
  -- 只置位会让 GUC 一直留到事务结束，同一个 HTTP 事务里后续任何直接写计数都会被放行。
  prev := current_setting('danshi.allow_counter_write', true);
  PERFORM set_config('danshi.allow_counter_write', 'on', true);
  IF TG_OP = 'INSERT' THEN
    UPDATE comments SET like_count = like_count + 1 WHERE id = NEW.comment_id;
    PERFORM set_config('danshi.allow_counter_write', COALESCE(prev, ''), true);
    RETURN NEW;
  END IF;
  UPDATE comments SET like_count = GREATEST(like_count - 1, 0) WHERE id = OLD.comment_id;
  PERFORM set_config('danshi.allow_counter_write', COALESCE(prev, ''), true);
  RETURN OLD;
END;
$func$;
-- +goose StatementEnd

CREATE TRIGGER trg_comment_likes_sync_count
    AFTER INSERT OR DELETE ON comment_likes
    FOR EACH ROW EXECUTE FUNCTION danshi_sync_comment_like_count();

-- 评论数与楼中楼回复数：一次插入/删除同时影响 posts.comment_count 与楼主 reply_count。
-- 软删除后行还在，但不应再计数，因此 deleted_at 的翻转也要走同一套增减逻辑：
--   INSERT（未删）        → +1
--   DELETE（原本未删）    → -1
--   UPDATE NULL → 非 NULL → -1（软删）
--   UPDATE 非 NULL → NULL → +1（恢复误杀）
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION danshi_sync_comment_counts()
RETURNS trigger
LANGUAGE plpgsql
AS $func$
DECLARE
  delta int := 0;
  p_id  bigint;
  r_id  bigint;
  prev  text;
BEGIN
  prev := current_setting('danshi.allow_counter_write', true);
  PERFORM set_config('danshi.allow_counter_write', 'on', true);
  IF TG_OP = 'INSERT' THEN
    IF NEW.deleted_at IS NULL THEN delta := 1; END IF;
    p_id := NEW.post_id; r_id := NEW.root_id;
  ELSIF TG_OP = 'DELETE' THEN
    IF OLD.deleted_at IS NULL THEN delta := -1; END IF;
    p_id := OLD.post_id; r_id := OLD.root_id;
  ELSE  -- UPDATE：只关心 deleted_at 的翻转
    IF    OLD.deleted_at IS NULL AND NEW.deleted_at IS NOT NULL THEN delta := -1;
    ELSIF OLD.deleted_at IS NOT NULL AND NEW.deleted_at IS NULL THEN delta := 1;
    END IF;
    p_id := NEW.post_id; r_id := NEW.root_id;
  END IF;

  IF delta <> 0 THEN
    UPDATE posts SET comment_count = GREATEST(comment_count + delta, 0) WHERE id = p_id;
    -- reply_count 记在楼主评论上，统计整层楼（拍扁呈现所需），按 root_id 归集
    IF r_id IS NOT NULL THEN
      UPDATE comments SET reply_count = GREATEST(reply_count + delta, 0) WHERE id = r_id;
    END IF;
  END IF;

  PERFORM set_config('danshi.allow_counter_write', COALESCE(prev, ''), true);
  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END;
$func$;
-- +goose StatementEnd

CREATE TRIGGER trg_comments_sync_counts
    AFTER INSERT OR DELETE ON comments
    FOR EACH ROW EXECUTE FUNCTION danshi_sync_comment_counts();

CREATE TRIGGER trg_comments_sync_counts_on_softdelete
    AFTER UPDATE OF deleted_at ON comments
    FOR EACH ROW
    WHEN (OLD.deleted_at IS DISTINCT FROM NEW.deleted_at)
    EXECUTE FUNCTION danshi_sync_comment_counts();

-- 计数器是触发器维护的派生列，业务代码不得直接写。
-- 「应用层禁止直接写」写在注释里不构成防线，这里靠触发器挡住：
-- 只有在同一事务内 SET LOCAL danshi.allow_counter_write = 'on' 才放行，
-- 该逃生阀由计数器同步触发器、danshi_recount_all() 与 ETL 使用。
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION danshi_forbid_counter_write()
RETURNS trigger
LANGUAGE plpgsql
AS $func$
BEGIN
  IF current_setting('danshi.allow_counter_write', true) IS NOT DISTINCT FROM 'on' THEN
    RETURN NEW;
  END IF;
  RAISE EXCEPTION
    '% 的计数列由触发器维护，业务代码不得直接写；'
    '新建行的计数列必须为 0，重算请用 danshi_recount_all()，'
    'ETL 请在事务内 SET LOCAL danshi.allow_counter_write = ''on''',
    TG_TABLE_NAME
    USING ERRCODE = 'restrict_violation';
END;
$func$;
-- +goose StatementEnd

-- UPDATE：任何改动计数列的直接写都要拦
CREATE TRIGGER trg_posts_counters_readonly
    BEFORE UPDATE OF like_count, favorite_count, comment_count ON posts
    FOR EACH ROW
    WHEN (OLD.like_count     IS DISTINCT FROM NEW.like_count
       OR OLD.favorite_count IS DISTINCT FROM NEW.favorite_count
       OR OLD.comment_count  IS DISTINCT FROM NEW.comment_count)
    EXECUTE FUNCTION danshi_forbid_counter_write();

CREATE TRIGGER trg_comments_counters_readonly
    BEFORE UPDATE OF like_count, reply_count ON comments
    FOR EACH ROW
    WHEN (OLD.like_count  IS DISTINCT FROM NEW.like_count
       OR OLD.reply_count IS DISTINCT FROM NEW.reply_count)
    EXECUTE FUNCTION danshi_forbid_counter_write();

-- INSERT：只挡 UPDATE 是不够的，建帖时可以直接灌 like_count=999，
-- 之后关联表触发器只会在这个错误基数上增减，永远回不到真值。
-- view_count 也要挡：UPDATE 时它必须能自增（浏览详情），但 INSERT 时没有理由非 0。
CREATE TRIGGER trg_posts_counters_insert_zero
    BEFORE INSERT ON posts
    FOR EACH ROW
    WHEN (NEW.like_count <> 0 OR NEW.favorite_count <> 0
       OR NEW.comment_count <> 0 OR NEW.view_count <> 0)
    EXECUTE FUNCTION danshi_forbid_counter_write();

CREATE TRIGGER trg_comments_counters_insert_zero
    BEFORE INSERT ON comments
    FOR EACH ROW
    WHEN (NEW.like_count <> 0 OR NEW.reply_count <> 0)
    EXECUTE FUNCTION danshi_forbid_counter_write();

-- 供 ETL 与 CI 一致性断言使用：全量重算所有计数器，返回被修正的行数。
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION danshi_recount_all()
RETURNS TABLE (table_name text, fixed_rows bigint)
LANGUAGE plpgsql
AS $func$
DECLARE
  n bigint;
  prev text;
BEGIN
  prev := current_setting('danshi.allow_counter_write', true);
  PERFORM set_config('danshi.allow_counter_write', 'on', true);
  WITH actual AS (
    SELECT p.id,
           (SELECT count(*) FROM post_likes  pl WHERE pl.post_id = p.id) AS lc,
           (SELECT count(*) FROM favorites   f  WHERE f.post_id  = p.id) AS fc,
           (SELECT count(*) FROM comments    c  WHERE c.post_id  = p.id
                                               AND c.deleted_at IS NULL) AS cc
    FROM posts p
  ), upd AS (
    UPDATE posts p
       SET like_count = a.lc, favorite_count = a.fc, comment_count = a.cc
      FROM actual a
     WHERE p.id = a.id
       AND (p.like_count, p.favorite_count, p.comment_count) IS DISTINCT FROM (a.lc, a.fc, a.cc)
    RETURNING 1
  ) SELECT count(*) INTO n FROM upd;
  table_name := 'posts'; fixed_rows := n; RETURN NEXT;

  WITH actual AS (
    SELECT c.id,
           (SELECT count(*) FROM comment_likes cl WHERE cl.comment_id = c.id) AS lc,
           (SELECT count(*) FROM comments       r WHERE r.root_id      = c.id
                                                    AND r.deleted_at IS NULL) AS rc
    FROM comments c
  ), upd AS (
    UPDATE comments c
       SET like_count = a.lc, reply_count = a.rc
      FROM actual a
     WHERE c.id = a.id
       AND (c.like_count, c.reply_count) IS DISTINCT FROM (a.lc, a.rc)
    RETURNING 1
  ) SELECT count(*) INTO n FROM upd;
  table_name := 'comments'; fixed_rows := n; RETURN NEXT;
  PERFORM set_config('danshi.allow_counter_write', COALESCE(prev, ''), true);
END;
$func$;
-- +goose StatementEnd

COMMENT ON FUNCTION danshi_recount_all() IS
  'ETL 装载完成后必须调用一次；CI 一致性断言应断言其返回的 fixed_rows 全为 0。'
  '因 schema 无 updated_at 触发器，重算不会污染业务时间戳。';


-- ============================================================
-- 图片资产退役：由外键关系驱动，不再做 URL 字符串匹配
-- ============================================================

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION danshi_retire_asset_if_unreferenced(p_asset_id bigint)
RETURNS void
LANGUAGE plpgsql
AS $func$
BEGIN
  IF p_asset_id IS NULL THEN
    RETURN;
  END IF;
  -- 这里显式写 updated_at：资产状态流转是本函数自己的业务语义，
  -- 与被移除的通用 updated_at 触发器无关。
  UPDATE image_assets AS a
     SET status = 'retired', updated_at = now()
   WHERE a.id = p_asset_id
     AND a.status = 'ready'
     AND NOT EXISTS (SELECT 1 FROM post_images pi WHERE pi.image_asset_id = a.id)
     AND NOT EXISTS (SELECT 1 FROM users u WHERE u.avatar_image_asset_id = a.id);
END;
$func$;
-- +goose StatementEnd

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION danshi_retire_post_image_asset()
RETURNS trigger
LANGUAGE plpgsql
AS $func$
BEGIN
  PERFORM danshi_retire_asset_if_unreferenced(OLD.image_asset_id);
  RETURN OLD;
END;
$func$;
-- +goose StatementEnd

CREATE TRIGGER trg_post_images_retire_asset
    AFTER DELETE ON post_images
    FOR EACH ROW EXECUTE FUNCTION danshi_retire_post_image_asset();

-- 反方向：重新引用一张已退役的资产时要让它复活，否则「删除后可再次创建」
-- 在行级成立、在资产状态上却是错的（实测删→retired→再插入仍是 retired）。
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION danshi_activate_post_image_asset()
RETURNS trigger
LANGUAGE plpgsql
AS $func$
BEGIN
  UPDATE image_assets
     SET status = 'ready', updated_at = now()
   WHERE id = NEW.image_asset_id
     AND status <> 'ready';
  RETURN NEW;
END;
$func$;
-- +goose StatementEnd

CREATE TRIGGER trg_post_images_activate_asset
    AFTER INSERT ON post_images
    FOR EACH ROW EXECUTE FUNCTION danshi_activate_post_image_asset();

-- 关联键不可变：改 image_asset_id 会绕过旧资产的退役检查。换图请删除后重建。
CREATE TRIGGER trg_post_images_keys_immutable
    BEFORE UPDATE OF post_id, image_asset_id ON post_images
    FOR EACH ROW
    WHEN (OLD.post_id IS DISTINCT FROM NEW.post_id
       OR OLD.image_asset_id IS DISTINCT FROM NEW.image_asset_id)
    EXECUTE FUNCTION danshi_forbid_key_update();

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION danshi_retire_avatar_asset()
RETURNS trigger
LANGUAGE plpgsql
AS $func$
BEGIN
  IF TG_OP = 'DELETE' THEN
    PERFORM danshi_retire_asset_if_unreferenced(OLD.avatar_image_asset_id);
    RETURN OLD;
  END IF;
  IF OLD.avatar_image_asset_id IS DISTINCT FROM NEW.avatar_image_asset_id THEN
    PERFORM danshi_retire_asset_if_unreferenced(OLD.avatar_image_asset_id);
  END IF;
  RETURN NEW;
END;
$func$;
-- +goose StatementEnd

CREATE TRIGGER trg_users_retire_avatar_asset
    AFTER UPDATE OF avatar_image_asset_id OR DELETE ON users
    FOR EACH ROW EXECUTE FUNCTION danshi_retire_avatar_asset();


-- +goose Down

DROP TRIGGER IF EXISTS trg_users_retire_avatar_asset  ON users;
DROP TRIGGER IF EXISTS trg_post_images_keys_immutable ON post_images;
DROP TRIGGER IF EXISTS trg_post_images_activate_asset ON post_images;
DROP FUNCTION IF EXISTS danshi_activate_post_image_asset();
DROP TRIGGER IF EXISTS trg_post_images_retire_asset   ON post_images;
DROP FUNCTION IF EXISTS danshi_retire_avatar_asset();
DROP FUNCTION IF EXISTS danshi_retire_post_image_asset();
DROP FUNCTION IF EXISTS danshi_retire_asset_if_unreferenced(bigint);

DROP TRIGGER IF EXISTS trg_comments_counters_insert_zero ON comments;
DROP TRIGGER IF EXISTS trg_posts_counters_insert_zero    ON posts;
DROP TRIGGER IF EXISTS trg_comments_counters_readonly ON comments;
DROP TRIGGER IF EXISTS trg_posts_counters_readonly    ON posts;
DROP FUNCTION IF EXISTS danshi_forbid_counter_write();
DROP FUNCTION IF EXISTS danshi_recount_all();
DROP TRIGGER IF EXISTS trg_comments_keys_immutable      ON comments;
DROP TRIGGER IF EXISTS trg_comment_likes_keys_immutable ON comment_likes;
DROP TRIGGER IF EXISTS trg_favorites_keys_immutable     ON favorites;
DROP TRIGGER IF EXISTS trg_post_likes_keys_immutable    ON post_likes;
DROP FUNCTION IF EXISTS danshi_forbid_key_update();
DROP TRIGGER IF EXISTS trg_comments_sync_counts_on_softdelete ON comments;
DROP TRIGGER IF EXISTS trg_comments_sync_counts      ON comments;
DROP TRIGGER IF EXISTS trg_comment_likes_sync_count  ON comment_likes;
DROP TRIGGER IF EXISTS trg_favorites_sync_count      ON favorites;
DROP TRIGGER IF EXISTS trg_post_likes_sync_count     ON post_likes;
DROP FUNCTION IF EXISTS danshi_sync_comment_counts();
DROP FUNCTION IF EXISTS danshi_sync_comment_like_count();
DROP FUNCTION IF EXISTS danshi_sync_post_favorite_count();
DROP FUNCTION IF EXISTS danshi_sync_post_like_count();

DROP TRIGGER IF EXISTS trg_ds_transition    ON dictionary_suggestions;
DROP TRIGGER IF EXISTS trg_ds_forbid_delete ON dictionary_suggestions;
DROP FUNCTION IF EXISTS danshi_check_suggestion_transition();
DROP TABLE IF EXISTS dictionary_suggestions;
DROP TRIGGER IF EXISTS trg_moderation_records_check_review    ON moderation_records;
DROP FUNCTION IF EXISTS danshi_check_moderation_review();
DROP TRIGGER IF EXISTS trg_moderation_records_forbid_delete ON moderation_records;
DROP TRIGGER IF EXISTS trg_moderation_records_immutable ON moderation_records;
DROP FUNCTION IF EXISTS danshi_forbid_moderation_rewrite();
DROP TRIGGER IF EXISTS trg_comment_histories_forbid_delete ON comment_histories;
DROP TRIGGER IF EXISTS trg_comment_histories_immutable     ON comment_histories;
DROP TRIGGER IF EXISTS trg_post_histories_forbid_delete    ON post_histories;
DROP TRIGGER IF EXISTS trg_post_histories_immutable        ON post_histories;
DROP TABLE IF EXISTS moderation_records;
DROP TABLE IF EXISTS comment_histories;
DROP TABLE IF EXISTS post_histories;
DROP TABLE IF EXISTS user_sessions;
DROP TABLE IF EXISTS email_verification_codes;
DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS comment_likes;
DROP TABLE IF EXISTS post_likes;
DROP TABLE IF EXISTS favorites;
DROP TABLE IF EXISTS follows;
DROP TABLE IF EXISTS comment_mentions;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS post_images;
DROP TABLE IF EXISTS post_flavors;
DROP TABLE IF EXISTS post_tags;
DROP TABLE IF EXISTS posts;

DROP TRIGGER IF EXISTS trg_users_forbid_delete    ON users;
DROP TRIGGER IF EXISTS trg_posts_forbid_delete    ON posts;
DROP TRIGGER IF EXISTS trg_comments_forbid_delete ON comments;
DROP TRIGGER IF EXISTS trg_tags_forbid_delete     ON tags;
DROP FUNCTION IF EXISTS danshi_forbid_hard_delete();
DROP FUNCTION IF EXISTS danshi_forbid_row_update();
ALTER TABLE IF EXISTS users DROP CONSTRAINT IF EXISTS fk_users_banned_by;
ALTER TABLE IF EXISTS users DROP CONSTRAINT IF EXISTS fk_users_avatar_image_asset;
DROP FUNCTION IF EXISTS danshi_purge_image_assets(bigint[]);
DROP TRIGGER IF EXISTS trg_image_assets_forbid_delete ON image_assets;
DROP FUNCTION IF EXISTS danshi_forbid_image_asset_delete();
DROP TABLE IF EXISTS image_assets;
DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS flavors;
DROP TABLE IF EXISTS cuisines;
DROP TABLE IF EXISTS canteen_windows;
DROP TABLE IF EXISTS canteens;
