-- +goose Up

-- 多角色绑定是纯关联：撤销时物理删除，再次授予时可重建。
CREATE TABLE user_roles (
    user_id    bigint      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role       varchar(20) NOT NULL,
    granted_by bigint      REFERENCES users (id) ON DELETE RESTRICT,
    granted_at timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (user_id, role),
    CONSTRAINT user_roles_role_check
        CHECK (role IN ('dict_reviewer', 'moderator', 'super_admin'))
);

CREATE INDEX idx_user_roles_role ON user_roles (role, granted_at DESC, user_id);

COMMENT ON TABLE user_roles IS
  '用户当前生效的管理角色绑定。普通用户不写绑定；撤销物理删行，再次授予可重建。';
COMMENT ON COLUMN user_roles.granted_by IS
  '授予角色的操作者；存量 users.role 迁移无法可靠还原操作者，因此迁移行允许为空。';

CREATE TABLE user_ban_records (
    id               bigint       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id          bigint       NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    action           varchar(10)  NOT NULL,
    ban_is_permanent boolean      NOT NULL DEFAULT false,
    banned_until     timestamptz,
    reason           varchar(200),
    actor_id         bigint       REFERENCES users (id) ON DELETE RESTRICT,
    created_at       timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT user_ban_records_action_check CHECK (action IN ('ban', 'unban')),
    CONSTRAINT user_ban_records_kind_check
        CHECK (NOT (ban_is_permanent AND banned_until IS NOT NULL)),
    CONSTRAINT user_ban_records_until_finite_check
        CHECK (banned_until IS NULL OR isfinite(banned_until)),
    CONSTRAINT user_ban_records_fields_check CHECK (
        CASE WHEN action = 'ban'
             THEN (ban_is_permanent OR banned_until IS NOT NULL)
                  AND reason IS NOT NULL AND btrim(reason) <> ''
             ELSE NOT ban_is_permanent AND banned_until IS NULL AND reason IS NULL
        END
    )
);

CREATE INDEX idx_user_ban_records_user ON user_ban_records (user_id, created_at DESC, id DESC);

CREATE TRIGGER trg_user_ban_records_immutable
    BEFORE UPDATE ON user_ban_records
    FOR EACH ROW EXECUTE FUNCTION danshi_forbid_row_update();
CREATE TRIGGER trg_user_ban_records_forbid_delete
    BEFORE DELETE ON user_ban_records
    FOR EACH ROW EXECUTE FUNCTION danshi_forbid_hard_delete();

COMMENT ON TABLE user_ban_records IS
  '封禁与解封的追加不可篡改流水。当前状态仍在 users，历史理由只能从本表追溯。';
COMMENT ON COLUMN user_ban_records.actor_id IS
  '执行封禁或解封的操作者；存量封禁无法可靠还原时允许为空。';

CREATE TABLE user_role_records (
    id         bigint       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id    bigint       NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    role       varchar(20)  NOT NULL,
    action     varchar(10)  NOT NULL,
    actor_id   bigint       REFERENCES users (id) ON DELETE RESTRICT,
    created_at timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT user_role_records_role_check
        CHECK (role IN ('dict_reviewer', 'moderator', 'super_admin')),
    CONSTRAINT user_role_records_action_check CHECK (action IN ('grant', 'revoke'))
);

CREATE INDEX idx_user_role_records_user ON user_role_records (user_id, created_at DESC, id DESC);

CREATE TRIGGER trg_user_role_records_immutable
    BEFORE UPDATE ON user_role_records
    FOR EACH ROW EXECUTE FUNCTION danshi_forbid_row_update();
CREATE TRIGGER trg_user_role_records_forbid_delete
    BEFORE DELETE ON user_role_records
    FOR EACH ROW EXECUTE FUNCTION danshi_forbid_hard_delete();

COMMENT ON TABLE user_role_records IS
  '角色授予与撤销的追加不可篡改流水；当前绑定删除后，历史仍可追溯。';
COMMENT ON COLUMN user_role_records.actor_id IS
  '执行授予或撤销的操作者；存量角色迁移无法可靠还原时允许为空。';

-- 存量 admin 只迁为 moderator，不自动获得词表维护能力。
INSERT INTO user_roles (user_id, role, granted_by, granted_at)
SELECT id, 'moderator', NULL, updated_at
  FROM users
 WHERE role = 'admin';

INSERT INTO user_roles (user_id, role, granted_by, granted_at)
SELECT id, 'super_admin', NULL, updated_at
  FROM users
 WHERE role = 'super_admin';

INSERT INTO user_role_records (user_id, role, action, actor_id, created_at)
SELECT user_id, role, 'grant', granted_by, granted_at
  FROM user_roles;

-- 为仍处于封禁字段状态的存量用户补一条可追溯起点；过期的限时封禁也保留原事实。
INSERT INTO user_ban_records
    (user_id, action, ban_is_permanent, banned_until, reason, actor_id, created_at)
SELECT id, 'ban', ban_is_permanent, banned_until, ban_reason, banned_by, updated_at
  FROM users
 WHERE ban_is_permanent OR banned_until IS NOT NULL;

ALTER TABLE users DROP CONSTRAINT users_role_check;
ALTER TABLE users DROP COLUMN role;


-- +goose Down

ALTER TABLE users ADD COLUMN role varchar(20) NOT NULL DEFAULT 'user';

UPDATE users AS u
   SET role = CASE
       WHEN EXISTS (
           SELECT 1 FROM user_roles AS ur
            WHERE ur.user_id = u.id AND ur.role = 'super_admin'
       ) THEN 'super_admin'
       WHEN EXISTS (
           SELECT 1 FROM user_roles AS ur
            WHERE ur.user_id = u.id AND ur.role IN ('moderator', 'dict_reviewer')
       ) THEN 'admin'
       ELSE 'user'
   END;

ALTER TABLE users
    ADD CONSTRAINT users_role_check CHECK (role IN ('user', 'admin', 'super_admin'));
COMMENT ON COLUMN users.role IS
  '回滚兼容列：user 普通用户；admin 管理员；super_admin 超级管理员。';

DROP TRIGGER IF EXISTS trg_user_role_records_forbid_delete ON user_role_records;
DROP TRIGGER IF EXISTS trg_user_role_records_immutable ON user_role_records;
DROP TABLE user_role_records;

DROP TRIGGER IF EXISTS trg_user_ban_records_forbid_delete ON user_ban_records;
DROP TRIGGER IF EXISTS trg_user_ban_records_immutable ON user_ban_records;
DROP TABLE user_ban_records;

DROP TABLE user_roles;
