-- name 的公开值只在通过同步机审后才会改变；本表记录已经生效的旧值、新值与时间。

-- +goose Up

CREATE TABLE user_name_change_records (
    id         bigint       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id    bigint       NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    old_name   varchar(24)  NOT NULL,
    new_name   varchar(24)  NOT NULL,
    changed_at timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT user_name_change_records_name_check CHECK (
        old_name = btrim(old_name)
        AND old_name = normalize(old_name, NFKC)
        AND char_length(old_name) BETWEEN 2 AND 24
        AND old_name ~ '^[[:alpha:][:digit:]_]+$'
        AND new_name = btrim(new_name)
        AND new_name = normalize(new_name, NFKC)
        AND char_length(new_name) BETWEEN 2 AND 24
        AND new_name ~ '^[[:alpha:][:digit:]_]+$'
        AND old_name <> new_name
    )
);

CREATE INDEX idx_user_name_change_records_user
    ON user_name_change_records (user_id, changed_at DESC, id DESC);

-- 00018 已经为 users.name 安装了统一占用触发器；在同一触发器中追加审计，保证导入、
-- 运维脚本等直写路径也不会绕过“修改前/修改后/时间”记录。应用层只负责审核后更新，
-- 不重复插入审计行。
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION danshi_claim_user_name()
RETURNS trigger
LANGUAGE plpgsql
AS $func$
DECLARE
    owner_id bigint;
    inserted integer;
BEGIN
    INSERT INTO user_name_claims (user_id, name, created_at)
    VALUES (NEW.id, NEW.name, NEW.created_at)
    ON CONFLICT DO NOTHING;
    GET DIAGNOSTICS inserted = ROW_COUNT;
    IF inserted = 1 THEN
        IF TG_OP = 'UPDATE' AND OLD.name IS DISTINCT FROM NEW.name THEN
            INSERT INTO user_name_change_records (user_id, old_name, new_name, changed_at)
            VALUES (NEW.id, OLD.name, NEW.name, now());
        END IF;
        RETURN NEW;
    END IF;

    SELECT user_id INTO owner_id
    FROM user_name_claims
    WHERE lower(normalize(name, NFKC)) = lower(normalize(NEW.name, NFKC));
    IF owner_id IS DISTINCT FROM NEW.id THEN
        RAISE EXCEPTION 'name 已被其他账号占用'
            USING ERRCODE = 'unique_violation', CONSTRAINT = 'uq_user_name_claims_name_lower';
    END IF;
    IF TG_OP = 'UPDATE' AND OLD.name IS DISTINCT FROM NEW.name THEN
        INSERT INTO user_name_change_records (user_id, old_name, new_name, changed_at)
        VALUES (NEW.id, OLD.name, NEW.name, now());
    END IF;
    RETURN NEW;
END;
$func$;
-- +goose StatementEnd

CREATE TRIGGER trg_user_name_change_records_immutable
    BEFORE UPDATE ON user_name_change_records
    FOR EACH ROW EXECUTE FUNCTION danshi_forbid_row_update();

CREATE TRIGGER trg_user_name_change_records_forbid_delete
    BEFORE DELETE ON user_name_change_records
    FOR EACH ROW EXECUTE FUNCTION danshi_forbid_hard_delete();

COMMENT ON TABLE user_name_change_records IS
    '已经生效的用户 name 变更审计。审核未通过的候选 name 不写入；历史记录不可修改或删除。';

-- +goose Down

DROP TRIGGER IF EXISTS trg_user_name_change_records_forbid_delete ON user_name_change_records;
DROP TRIGGER IF EXISTS trg_user_name_change_records_immutable ON user_name_change_records;
DROP TABLE IF EXISTS user_name_change_records;

-- 恢复 00018 的原始占用触发器，保证回到 version 18 后 users.name 仍可正常写入。
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION danshi_claim_user_name()
RETURNS trigger
LANGUAGE plpgsql
AS $func$
DECLARE
    owner_id bigint;
    inserted integer;
BEGIN
    INSERT INTO user_name_claims (user_id, name, created_at)
    VALUES (NEW.id, NEW.name, NEW.created_at)
    ON CONFLICT DO NOTHING;
    GET DIAGNOSTICS inserted = ROW_COUNT;
    IF inserted = 1 THEN
        RETURN NEW;
    END IF;

    SELECT user_id INTO owner_id
    FROM user_name_claims
    WHERE lower(normalize(name, NFKC)) = lower(normalize(NEW.name, NFKC));
    IF owner_id IS DISTINCT FROM NEW.id THEN
        RAISE EXCEPTION 'name 已被其他账号占用'
            USING ERRCODE = 'unique_violation', CONSTRAINT = 'uq_user_name_claims_name_lower';
    END IF;
    RETURN NEW;
END;
$func$;
-- +goose StatementEnd
