-- +goose Up

ALTER TABLE moderation_records
    ADD CONSTRAINT uq_mr_id_image UNIQUE (id, image_asset_id);

CREATE TABLE image_access_intents (
    id                          bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    image_asset_id              bigint NOT NULL REFERENCES image_assets(id) ON DELETE CASCADE,
    source_moderation_record_id bigint NOT NULL,
    desired_public              boolean NOT NULL,
    created_at                  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT fk_image_access_intent_source
        FOREIGN KEY (source_moderation_record_id, image_asset_id)
        REFERENCES moderation_records(id, image_asset_id) ON DELETE CASCADE,
    CONSTRAINT uq_image_access_intent_source UNIQUE (source_moderation_record_id),
    CONSTRAINT uq_image_access_intent_identity
        UNIQUE (id, image_asset_id, desired_public)
);

COMMENT ON TABLE image_access_intents IS
    '审核图片访问状态的追加意图；同一审核流水只产生一次意图';

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION danshi_validate_image_access_intent()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog
AS $func$
DECLARE source_verdict text;
BEGIN
    SELECT verdict INTO source_verdict
      FROM public.moderation_records
     WHERE id = NEW.source_moderation_record_id
       AND image_asset_id = NEW.image_asset_id;
    IF NOT FOUND OR NEW.desired_public IS DISTINCT FROM (source_verdict = 'pass') THEN
        RAISE EXCEPTION 'image access intent does not match moderation verdict'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$func$;
-- +goose StatementEnd

CREATE TRIGGER trg_image_access_intents_validate
    BEFORE INSERT ON image_access_intents
    FOR EACH ROW EXECUTE FUNCTION danshi_validate_image_access_intent();

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION danshi_forbid_image_access_intent_rewrite()
RETURNS trigger
LANGUAGE plpgsql
AS $func$
BEGIN
    IF TG_OP = 'DELETE'
       AND current_setting('danshi.allow_image_asset_delete', true) = 'on' THEN
        RETURN OLD;
    END IF;
    RAISE EXCEPTION 'image access intents are append-only'
        USING ERRCODE = 'object_not_in_prerequisite_state';
END;
$func$;
-- +goose StatementEnd

CREATE TRIGGER trg_image_access_intents_immutable
    BEFORE UPDATE OR DELETE ON image_access_intents
    FOR EACH ROW EXECUTE FUNCTION danshi_forbid_image_access_intent_rewrite();

CREATE TABLE image_access_deliveries (
    image_asset_id       bigint PRIMARY KEY REFERENCES image_assets(id) ON DELETE CASCADE,
    desired_intent_id    bigint NOT NULL UNIQUE,
    desired_public       boolean NOT NULL,
    purge_required       boolean NOT NULL DEFAULT true,
    generation           bigint NOT NULL DEFAULT 1 CHECK (generation > 0),
    state                text NOT NULL DEFAULT 'pending_acl'
                         CHECK (state IN (
                             'pending_acl', 'pending_submit', 'submitting',
                             'submitted', 'succeeded', 'dead_letter'
                         )),
    acl_attempts         integer NOT NULL DEFAULT 0 CHECK (acl_attempts >= 0),
    submit_attempts      integer NOT NULL DEFAULT 0 CHECK (submit_attempts >= 0),
    poll_attempts        integer NOT NULL DEFAULT 0 CHECK (poll_attempts >= 0),
    unknown_checks       integer NOT NULL DEFAULT 0 CHECK (unknown_checks >= 0),
    provider_job_id      text,
    submission_started_at timestamptz,
    next_attempt_at      timestamptz DEFAULT now(),
    lease_token          text,
    lease_until          timestamptz,
    last_error_code      text,
    completed_at         timestamptz,
    dead_lettered_at     timestamptz,
    created_at           timestamptz NOT NULL DEFAULT now(),
    updated_at           timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT fk_image_access_delivery_intent
        FOREIGN KEY (desired_intent_id, image_asset_id, desired_public)
        REFERENCES image_access_intents(id, image_asset_id, desired_public) ON DELETE CASCADE,
    CHECK ((lease_token IS NULL) = (lease_until IS NULL)),
    CHECK (lease_token IS NULL OR length(lease_token) BETWEEN 16 AND 64),
    CHECK (provider_job_id IS NULL OR length(provider_job_id) BETWEEN 1 AND 128),
    CHECK (last_error_code IS NULL OR last_error_code IN (
        'acl_retryable', 'acl_exhausted',
        'submit_retryable', 'submit_unknown', 'submit_permanent', 'submit_exhausted',
        'discover_retryable', 'discover_permanent', 'discover_exhausted',
        'poll_retryable', 'poll_permanent', 'provider_failed', 'provider_timeout',
        'provider_canceled', 'provider_pending_timeout', 'poll_exhausted'
    )),
    CHECK (state <> 'submitting' OR submission_started_at IS NOT NULL),
    CHECK (state <> 'submitted' OR (provider_job_id IS NOT NULL AND submission_started_at IS NOT NULL)),
    CHECK (state <> 'succeeded' OR completed_at IS NOT NULL),
    CHECK (state <> 'dead_letter' OR dead_lettered_at IS NOT NULL),
    CHECK (purge_required OR state IN ('pending_acl', 'succeeded', 'dead_letter')),
    CHECK ((state IN ('succeeded', 'dead_letter')) = (next_attempt_at IS NULL))
);

COMMENT ON TABLE image_access_deliveries IS
    '审核图片 ACL 与 EdgeOne 精确刷新事务 outbox；每个资产只保存最新期望状态，不保存 URL/对象键';

CREATE INDEX idx_image_access_deliveries_due
    ON image_access_deliveries (next_attempt_at, image_asset_id)
    WHERE state NOT IN ('succeeded', 'dead_letter');

CREATE INDEX idx_image_access_deliveries_lease
    ON image_access_deliveries (lease_until)
    WHERE lease_until IS NOT NULL;

-- v11 已经可能存在通过、待复核或违规的完成态资产。升级时必须把它们的
-- 当前审核事实投影进 durable outbox，否则旧 review/block 只能等待一次未来
-- 回调才会收敛 ACL/CDN。所有历史图片审核行都先 grandfather 为 immutable
-- intent，使旧 provider callback 的重复投递仍命中 source 幂等键；每张完成态
-- 图片再选择与当前 image_assets.moderation 一致的最新 intent 作为 delivery。
-- 历史状态转换无法从当前快照可靠重建，因此所有 grandfather delivery 都保守地
-- 标记 purge_required=true：这可能多刷一次，但不会漏掉曾以公开响应或 403 被缓存的 URL。
-- 找不到事实时中止迁移，避免静默留下不可交付资产。
-- +goose StatementBegin
DO $block$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM image_assets AS asset
        WHERE asset.moderation IN ('pass', 'review', 'block')
          AND asset.public_url <> ''
          AND asset.public_url NOT LIKE 'urn:danshi:image-asset:%:retired'
          AND NOT EXISTS (
              SELECT 1
              FROM moderation_records AS source
              WHERE source.image_asset_id = asset.id
                AND source.verdict = asset.moderation
          )
    ) THEN
        RAISE EXCEPTION
            'cannot grandfather image access outbox: terminal asset lacks matching moderation fact'
            USING ERRCODE = 'check_violation';
    END IF;
END;
$block$;
-- +goose StatementEnd

INSERT INTO image_access_intents
    (image_asset_id, source_moderation_record_id, desired_public, created_at)
SELECT image_asset_id, id, (verdict = 'pass'), now()
FROM moderation_records
WHERE image_asset_id IS NOT NULL
ORDER BY id;

INSERT INTO image_access_deliveries (
    image_asset_id, desired_intent_id, desired_public, purge_required, generation, state,
    next_attempt_at, created_at, updated_at
)
SELECT asset.id, desired.id, desired.desired_public, true, 1, 'pending_acl',
       now(), now(), now()
FROM image_assets AS asset
CROSS JOIN LATERAL (
    SELECT intent.id, intent.desired_public
    FROM image_access_intents AS intent
    JOIN moderation_records AS source
      ON source.id = intent.source_moderation_record_id
    WHERE intent.image_asset_id = asset.id
      AND source.verdict = asset.moderation
    ORDER BY source.created_at DESC, source.id DESC
    LIMIT 1
) AS desired
WHERE asset.moderation IN ('pass', 'review', 'block')
  AND asset.public_url <> ''
  AND asset.public_url NOT LIKE 'urn:danshi:image-asset:%:retired';


-- +goose Down

DROP TABLE IF EXISTS image_access_deliveries;
DROP TRIGGER IF EXISTS trg_image_access_intents_immutable ON image_access_intents;
DROP TRIGGER IF EXISTS trg_image_access_intents_validate ON image_access_intents;
DROP FUNCTION IF EXISTS danshi_forbid_image_access_intent_rewrite();
DROP FUNCTION IF EXISTS danshi_validate_image_access_intent();
DROP TABLE IF EXISTS image_access_intents;
ALTER TABLE moderation_records DROP CONSTRAINT IF EXISTS uq_mr_id_image;
