-- name 是用户对外的全局身份标识：当前值仍保存在 users.name，不新增 username 字段。
--
-- user_name_claims 保存每个已经归属过的 name。其唯一约束既保护并发注册，也保证注销与
-- 改名不会把历史作者身份交给另一账号。历史数据必须先消除空白与大小写不敏感重名，迁移
-- 才会继续；宁可明确阻止上线，也不能任意替用户生成或分配公开身份。

-- +goose Up

-- +goose StatementBegin
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM users
        WHERE name <> btrim(name) OR char_length(name) NOT BETWEEN 2 AND 24
    ) THEN
        RAISE EXCEPTION
            'name 身份化前必须为所有既有用户补设 2–24 个字符且无首尾空白的 name'
            USING ERRCODE = 'check_violation';
    END IF;
    IF EXISTS (
        SELECT 1 FROM users GROUP BY lower(name) HAVING count(*) > 1
    ) THEN
        RAISE EXCEPTION
            'name 身份化前必须消除大小写不敏感的重复 name'
            USING ERRCODE = 'unique_violation';
    END IF;
END;
$$;
-- +goose StatementEnd

ALTER TABLE users
    ADD CONSTRAINT users_name_identity_check CHECK (
        name = btrim(name) AND char_length(name) BETWEEN 2 AND 24
    );

CREATE UNIQUE INDEX uq_users_name_lower ON users (lower(name));

CREATE TABLE user_name_claims (
    id         bigint       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id    bigint       NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    name       varchar(100) NOT NULL,
    created_at timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT user_name_claims_name_check CHECK (
        name = btrim(name) AND char_length(name) BETWEEN 2 AND 24
    )
);

CREATE UNIQUE INDEX uq_user_name_claims_name_lower ON user_name_claims (lower(name));
CREATE INDEX idx_user_name_claims_user ON user_name_claims (user_id, created_at DESC);

INSERT INTO user_name_claims (user_id, name, created_at)
SELECT id, name, created_at FROM users;

-- 夹具、导入与运维脚本同样可能直接写 users。触发器把“当前 name 必须有归属记录、
-- 旧 name 不可被另一账号接管”落实为数据库防线；应用层仍先显式 ClaimName，以便将
-- 冲突转换为稳定业务错误而不是依赖触发器文案。
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION danshi_claim_user_name()
RETURNS trigger
LANGUAGE plpgsql
AS $func$
DECLARE
    owner_id bigint;
    inserted integer;
BEGIN
    INSERT INTO user_name_claims (user_id, name, created_at)
    VALUES (NEW.id, NEW.name, NEW.created_at)
    ON CONFLICT DO NOTHING;
    GET DIAGNOSTICS inserted = ROW_COUNT;
    IF inserted = 1 THEN
        RETURN NEW;
    END IF;

    SELECT user_id INTO owner_id
    FROM user_name_claims
    WHERE lower(name) = lower(NEW.name);
    IF owner_id IS DISTINCT FROM NEW.id THEN
        RAISE EXCEPTION 'name 已被其他账号占用'
            USING ERRCODE = 'unique_violation', CONSTRAINT = 'uq_user_name_claims_name_lower';
    END IF;
    RETURN NEW;
END;
$func$;
-- +goose StatementEnd

CREATE TRIGGER trg_users_claim_name
    AFTER INSERT OR UPDATE OF name ON users
    FOR EACH ROW EXECUTE FUNCTION danshi_claim_user_name();

CREATE TRIGGER trg_user_name_claims_forbid_update
    BEFORE UPDATE ON user_name_claims
    FOR EACH ROW EXECUTE FUNCTION danshi_forbid_row_update();

CREATE TRIGGER trg_user_name_claims_forbid_delete
    BEFORE DELETE ON user_name_claims
    FOR EACH ROW EXECUTE FUNCTION danshi_forbid_hard_delete();

COMMENT ON TABLE user_name_claims IS
    '用户 name 的追加占用记录。当前 name 在 users.name；所有历史 name 永久保留，防止改名或注销后身份被冒用。';

-- +goose Down

DROP TRIGGER IF EXISTS trg_user_name_claims_forbid_delete ON user_name_claims;
DROP TRIGGER IF EXISTS trg_user_name_claims_forbid_update ON user_name_claims;
DROP TRIGGER IF EXISTS trg_users_claim_name ON users;
DROP FUNCTION IF EXISTS danshi_claim_user_name();
DROP TABLE IF EXISTS user_name_claims;
DROP INDEX IF EXISTS uq_users_name_lower;
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_name_identity_check;
