-- 验证码邮件只在验证码状态落库后异步投递；密文使用 EMAIL_VERIFICATION_SECRET 加密。

-- +goose Up

CREATE TABLE verification_email_deliveries (
    id              bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    challenge_id    bigint NOT NULL REFERENCES email_verification_codes (id) ON DELETE CASCADE,
    email           varchar(255) NOT NULL,
    purpose         varchar(32) NOT NULL,
    code_digest     varchar(64) NOT NULL,
    code_ciphertext bytea NOT NULL,
    state           varchar(16) NOT NULL DEFAULT 'pending',
    attempts        integer NOT NULL DEFAULT 0,
    next_attempt_at timestamptz,
    lease_token     varchar(64),
    lease_until     timestamptz,
    last_error_code varchar(32),
    sent_at         timestamptz,
    canceled_at     timestamptz,
    dead_lettered_at timestamptz,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT verification_email_deliveries_purpose_check
        CHECK (purpose IN ('registration', 'password_reset')),
    CONSTRAINT verification_email_deliveries_digest_check
        CHECK (length(code_digest) = 64),
    CONSTRAINT verification_email_deliveries_ciphertext_check
        CHECK (octet_length(code_ciphertext) > 0),
    CONSTRAINT verification_email_deliveries_state_check
        CHECK (state IN ('pending', 'sending', 'sent', 'canceled', 'dead_letter')),
    CONSTRAINT verification_email_deliveries_attempts_check
        CHECK (attempts >= 0),
    CONSTRAINT verification_email_deliveries_lease_pair_check
        CHECK ((lease_token IS NULL) = (lease_until IS NULL)),
    CONSTRAINT verification_email_deliveries_lease_token_check
        CHECK (lease_token IS NULL OR length(lease_token) BETWEEN 16 AND 64),
    CONSTRAINT verification_email_deliveries_error_check
        CHECK (last_error_code IS NULL OR last_error_code IN (
            'stale_challenge', 'decrypt_failed', 'provider_error', 'delivery_exhausted'
        )),
    CONSTRAINT verification_email_deliveries_terminal_check
        CHECK (
            (state = 'sent') = (sent_at IS NOT NULL)
            AND (state = 'canceled') = (canceled_at IS NOT NULL)
            AND (state = 'dead_letter') = (dead_lettered_at IS NOT NULL)
            AND (state IN ('sent', 'canceled', 'dead_letter')) = (next_attempt_at IS NULL)
        )
);

CREATE INDEX idx_verification_email_deliveries_due
    ON verification_email_deliveries (next_attempt_at, id)
    WHERE state IN ('pending', 'sending');

COMMENT ON TABLE verification_email_deliveries IS
    '验证码邮件 durable outbox；邮箱可用于投递对账，验证码仅保存应用密钥加密后的密文。';
COMMENT ON COLUMN verification_email_deliveries.code_ciphertext IS
    '使用 EMAIL_VERIFICATION_SECRET 通过 AEAD 加密的验证码，不得写入明文。';

-- +goose Down

DROP TABLE verification_email_deliveries;
