// Package apierrcodes 从 apierr/codes.go 的常量声明生成可枚举的错误码目录。
package apierrcodes

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/constant"
	"go/format"
	"go/parser"
	"go/token"
	"go/types"
	"os"
	"strconv"
	"strings"
)

const (
	fieldCodeType = "FieldCode"
	bizCodeType   = "BizCode"
)

type code struct {
	name  string
	value string
}

// Generate 读取 codes.go，并按声明顺序生成 FieldCode 与 BizCode 的完整目录。
func Generate(input string) ([]byte, error) {
	fileSet := token.NewFileSet()
	parsed, err := parser.ParseFile(fileSet, input, nil, 0)
	if err != nil {
		return nil, fmt.Errorf("解析错误码源文件: %w", err)
	}
	fieldCodes, bizCodes, err := collectCodes(fileSet, parsed)
	if err != nil {
		return nil, err
	}
	var generated bytes.Buffer
	generated.WriteString("// Code generated by apierrcodes; DO NOT EDIT.\n\n")
	generated.WriteString("package apierr\n\n")
	writeCatalog(&generated, "generatedFieldCodes", fieldCodeType, fieldCodes)
	writeCatalog(&generated, "generatedBizCodes", bizCodeType, bizCodes)
	generated.WriteString("// AllFieldCodes 返回 codes.go 中声明的全部字段级错误码。\n")
	generated.WriteString("func AllFieldCodes() []FieldCode {\n")
	generated.WriteString("\treturn append([]FieldCode(nil), generatedFieldCodes[:]...)\n")
	generated.WriteString("}\n\n")
	generated.WriteString("// AllBizCodes 返回 codes.go 中声明的全部业务错误码。\n")
	generated.WriteString("func AllBizCodes() []BizCode {\n")
	generated.WriteString("\treturn append([]BizCode(nil), generatedBizCodes[:]...)\n")
	generated.WriteString("}\n")
	formatted, err := format.Source(generated.Bytes())
	if err != nil {
		return nil, fmt.Errorf("格式化错误码生成物: %w", err)
	}
	return formatted, nil
}

// Write 生成 output；check 为 true 时只检查已有文件，不写入。
func Write(input, output string, check bool) error {
	generated, err := Generate(input)
	if err != nil {
		return err
	}
	if check {
		current, readErr := os.ReadFile(output)
		if readErr != nil {
			return fmt.Errorf("读取错误码生成物: %w", readErr)
		}
		if !bytes.Equal(current, generated) {
			return fmt.Errorf("%s 已漂移；请运行 go generate ./internal/apierr", output)
		}
		return nil
	}
	if err := os.WriteFile(output, generated, 0o644); err != nil {
		return fmt.Errorf("写入错误码生成物: %w", err)
	}
	return nil
}

func collectCodes(fileSet *token.FileSet, file *ast.File) ([]code, []code, error) {
	definitions := make(map[*ast.Ident]types.Object)
	configuration := types.Config{}
	if _, err := configuration.Check("apierr", fileSet, []*ast.File{file}, &types.Info{Defs: definitions}); err != nil {
		return nil, nil, fmt.Errorf("类型检查错误码源文件: %w", err)
	}
	var fieldCodes, bizCodes []code
	seen := make(map[string]map[string]string)
	for _, declaration := range file.Decls {
		general, ok := declaration.(*ast.GenDecl)
		if !ok || general.Tok != token.CONST {
			continue
		}
		for _, rawSpec := range general.Specs {
			spec, ok := rawSpec.(*ast.ValueSpec)
			if !ok {
				continue
			}
			for _, name := range spec.Names {
				constantObject, ok := definitions[name].(*types.Const)
				if !ok {
					continue
				}
				typeName := namedTypeName(constantObject.Type())
				if typeName != fieldCodeType && typeName != bizCodeType {
					if strings.HasPrefix(name.Name, "Field") || strings.HasPrefix(name.Name, "Biz") {
						return nil, nil, fmt.Errorf("%s 必须显式声明为 FieldCode 或 BizCode", name.Name)
					}
					continue
				}
				if constantObject.Val().Kind() != constant.String {
					return nil, nil, fmt.Errorf("%s.%s 的值必须是非空字符串", typeName, name.Name)
				}
				value := constant.StringVal(constantObject.Val())
				if value == "" {
					return nil, nil, fmt.Errorf("%s.%s 的值必须是非空字符串", typeName, name.Name)
				}
				if err := rememberCode(typeName, name.Name, value, seen); err != nil {
					return nil, nil, err
				}
				item := code{name: name.Name, value: value}
				if typeName == fieldCodeType {
					fieldCodes = append(fieldCodes, item)
				} else {
					bizCodes = append(bizCodes, item)
				}
			}
		}
	}
	if len(fieldCodes) == 0 || len(bizCodes) == 0 {
		return nil, nil, fmt.Errorf("codes.go 必须同时声明 FieldCode 与 BizCode 常量")
	}
	return fieldCodes, bizCodes, nil
}

func namedTypeName(valueType types.Type) string {
	named, ok := valueType.(*types.Named)
	if !ok {
		return ""
	}
	return named.Obj().Name()
}

func rememberCode(typeName, name, value string, seen map[string]map[string]string) error {
	if seen[typeName] == nil {
		seen[typeName] = make(map[string]string)
	}
	if previous := seen[typeName][value]; previous != "" {
		return fmt.Errorf("%s.%s 与 %s 的值 %q 重复", typeName, name, previous, value)
	}
	seen[typeName][value] = name
	return nil
}

func writeCatalog(buffer *bytes.Buffer, variable, typeName string, codes []code) {
	_, _ = fmt.Fprintf(buffer, "var %s = [...]%s{\n", variable, typeName)
	for _, item := range codes {
		_, _ = fmt.Fprintf(buffer, "\t%s, // %s\n", item.name, strconv.Quote(item.value))
	}
	buffer.WriteString("}\n\n")
}
