// Code generated by apierrcodes; DO NOT EDIT.

package apierr

var generatedFieldCodes = [...]FieldCode{
	FieldRequired,      // "required"
	FieldTooLong,       // "too_long"
	FieldTooShort,      // "too_short"
	FieldOutOfRange,    // "out_of_range"
	FieldInvalidFormat, // "invalid_format"
	FieldInvalidEnum,   // "invalid_enum"
	FieldInvalidDomain, // "invalid_domain"
	FieldConflict,      // "conflict"
}

var generatedBizCodes = [...]BizCode{
	BizInternal,                  // "internal_error"
	BizNotFound,                  // "not_found"
	BizMethodNotAllowed,          // "method_not_allowed"
	BizValidation,                // "validation_failed"
	BizRateLimited,               // "rate_limited"
	BizUnauthorized,              // "unauthorized"
	BizServiceUnavailable,        // "service_unavailable"
	BizEmailTaken,                // "email_taken"
	BizEmailDomainNotAllow,       // "email_domain_not_allow"
	BizCredentialsInvalid,        // "credentials_invalid"
	BizVerifyCodeInvalid,         // "verify_code_invalid"
	BizVerifyCodeTooMany,         // "verify_code_too_many"
	BizVerifyCodeBusy,            // "verify_code_busy"
	BizAccountBanned,             // "account_banned"
	BizAccountDeleted,            // "account_deleted"
	BizSessionRevoked,            // "session_revoked"
	BizSessionNotFound,           // "session_not_found"
	BizPermissionDenied,          // "permission_denied"
	BizNotOwner,                  // "not_owner"
	BizPostNotFound,              // "post_not_found"
	BizPostNotPublished,          // "post_not_published"
	BizPostDeleted,               // "post_deleted"
	BizCommentNotFound,           // "comment_not_found"
	BizCommentDeleted,            // "comment_deleted"
	BizNotificationNotFound,      // "notification_not_found"
	BizContentUnderAudit,         // "content_under_audit"
	BizContentRejected,           // "content_rejected"
	BizContentNotRestorable,      // "content_not_restorable"
	BizModerationNotPending,      // "moderation_not_pending"
	BizDictItemNotFound,          // "dict_item_not_found"
	BizDictItemInUse,             // "dict_item_in_use"
	BizWindowNotInCanteen,        // "window_not_in_canteen"
	BizSuggestionNotFound,        // "suggestion_not_found"
	BizSuggestionClosed,          // "suggestion_closed"
	BizSuggestionParentPending,   // "suggestion_parent_pending"
	BizTagLimitExceeded,          // "tag_limit_exceeded"
	BizImageNotFound,             // "image_not_found"
	BizImageNotOwned,             // "image_not_owned"
	BizImagePurposeWrong,         // "image_purpose_wrong"
	BizImageNotApproved,          // "image_not_approved"
	BizUploadNotFound,            // "upload_not_found"
	BizUploadClosed,              // "upload_closed"
	BizUploadIncomplete,          // "upload_incomplete"
	BizUploadSizeMismatch,        // "upload_size_mismatch"
	BizModerationCallbackInvalid, // "moderation_callback_invalid"
	BizCannotFollowSelf,          // "cannot_follow_self"
	BizAlreadyExists,             // "already_exists"
	BizConflict,                  // "conflict"
}

// AllFieldCodes 返回 codes.go 中声明的全部字段级错误码。
func AllFieldCodes() []FieldCode {
	return append([]FieldCode(nil), generatedFieldCodes[:]...)
}

// AllBizCodes 返回 codes.go 中声明的全部业务错误码。
func AllBizCodes() []BizCode {
	return append([]BizCode(nil), generatedBizCodes[:]...)
}
